import { __ } from '../../../Utils/i18nwrap'

export const modules = [
  { name: 'create_cpt', label: __('Create CPT', 'bit-integrations'), is_pro: false },
  { name: 'update_cpt', label: __('Update CPT', 'bit-integrations'), is_pro: true },
  { name: 'delete_cpt', label: __('Delete CPT', 'bit-integrations'), is_pro: true },
  { name: 'create_taxonomy', label: __('Create Taxonomy', 'bit-integrations'), is_pro: true },
  { name: 'update_taxonomy', label: __('Update Taxonomy', 'bit-integrations'), is_pro: true },
  { name: 'delete_taxonomy', label: __('Delete Taxonomy', 'bit-integrations'), is_pro: true },
  {
    name: 'associate_taxonomy_to_cpt',
    label: __('Associate Taxonomy To CPT', 'bit-integrations'),
    is_pro: true
  },
  { name: 'create_option_page', label: __('Create Option Page', 'bit-integrations'), is_pro: true },
  { name: 'update_option_page', label: __('Update Option Page', 'bit-integrations'), is_pro: true },
  { name: 'delete_option_page', label: __('Delete Option Page', 'bit-integrations'), is_pro: true },
  { name: 'delete_meta_group', label: __('Delete Meta Field Group', 'bit-integrations'), is_pro: true },
  { name: 'delete_dynamic_block', label: __('Delete Dynamic Block', 'bit-integrations'), is_pro: true }
]

export const cptFields = [
  { label: __('Post Name', 'bit-integrations'), key: 'post_name', required: true },
  { label: __('Singular Label', 'bit-integrations'), key: 'singular_label', required: true },
  { label: __('Plural Label', 'bit-integrations'), key: 'plural_label', required: true },
  { label: __('REST API base slug', 'bit-integrations'), key: 'rest_base', required: false },
  { label: __('Menu position', 'bit-integrations'), key: 'menu_position', required: false },
  { label: __('Capability type', 'bit-integrations'), key: 'capability_type', required: false },
  { label: __('Custom rewrite rules', 'bit-integrations'), key: 'custom_rewrite', required: false },
  { label: __('Custom query var', 'bit-integrations'), key: 'custom_query_var', required: false }
]

export const cptLabels = [
  { label: __('Menu Name', 'bit-integrations'), key: 'menu_name' },
  { label: __('All Items', 'bit-integrations'), key: 'all_items' },
  { label: __('Add New', 'bit-integrations'), key: 'add_new' },
  { label: __('Add New Item', 'bit-integrations'), key: 'add_new_item' },
  { label: __('Edit Item', 'bit-integrations'), key: 'edit_item' },
  { label: __('New Item', 'bit-integrations'), key: 'new_item' },
  { label: __('View Item', 'bit-integrations'), key: 'view_item' },
  { label: __('View Items', 'bit-integrations'), key: 'view_items' },
  { label: __('Search Item', 'bit-integrations'), key: 'search_item' },
  { label: __('Not Found', 'bit-integrations'), key: 'not_found' },
  { label: __('Not Found in Trash', 'bit-integrations'), key: 'not_found_in_trash' },
  { label: __('Parent Item Colon', 'bit-integrations'), key: 'parent_item_colon' },
  { label: __('Featured Image', 'bit-integrations'), key: 'featured_image' },
  { label: __('Set Featured Image', 'bit-integrations'), key: 'set_featured_image' },
  { label: __('Remove Featured Image', 'bit-integrations'), key: 'remove_featured_image' },
  { label: __('Use Featured Image', 'bit-integrations'), key: 'use_featured_image' },
  { label: __('Archives', 'bit-integrations'), key: 'archives' },
  { label: __('Insert into Item', 'bit-integrations'), key: 'insert_into_item' },
  { label: __('Uploaded to This Item', 'bit-integrations'), key: 'uploaded_to_this_item' },
  { label: __('Filter Items List', 'bit-integrations'), key: 'filter_items_list' },
  { label: __('Items List Navigation', 'bit-integrations'), key: 'items_list_navigation' },
  { label: __('Items List', 'bit-integrations'), key: 'items_list' },
  { label: __('Filter by Date', 'bit-integrations'), key: 'filter_by_date' },
  { label: __('Item Published', 'bit-integrations'), key: 'item_published' },
  { label: __('Item Published Privately', 'bit-integrations'), key: 'item_published_privately' },
  { label: __('Item Reverted to Draft', 'bit-integrations'), key: 'item_reverted_to_draft' },
  { label: __('Item Scheduled', 'bit-integrations'), key: 'item_scheduled' },
  { label: __('Item Updated', 'bit-integrations'), key: 'item_updated' }
]

export const taxonomyLabels = [
  { label: __('Menu Name', 'bit-integrations'), key: 'name' },
  { label: __('Singular name', 'bit-integrations'), key: 'singular_name' },
  { label: __('Search Items', 'bit-integrations'), key: 'search_items' },
  { label: __('Popular Items', 'bit-integrations'), key: 'popular_items' },
  { label: __('All Items', 'bit-integrations'), key: 'all_items' },
  { label: __('Parent Item', 'bit-integrations'), key: 'parent_item' },
  { label: __('Parent Item Colon', 'bit-integrations'), key: 'parent_item_colon' },
  { label: __('Edit Item', 'bit-integrations'), key: 'edit_item' },
  { label: __('View Item', 'bit-integrations'), key: 'view_item' },
  { label: __('Update Item', 'bit-integrations'), key: 'update_item' },
  { label: __('Add New Item', 'bit-integrations'), key: 'add_new_item' },
  { label: __('New Item Name', 'bit-integrations'), key: 'new_item_name' },
  {
    label: __('Separate Items With Commas', 'bit-integrations'),
    key: 'separate_items_with_commas'
  },
  { label: __('Add or Remove Items', 'bit-integrations'), key: 'add_or_remove_items' },
  {
    label: __('Choose From Most Used', 'bit-integrations'),
    key: 'choose_from_most_used'
  },
  { label: __('Not Found', 'bit-integrations'), key: 'not_found' },
  { label: __('No Terms', 'bit-integrations'), key: 'no_terms' },
  { label: __('Filter By Item', 'bit-integrations'), key: 'filter_by_item' },
  {
    label: __('Items List Navigation', 'bit-integrations'),
    key: 'items_list_navigation'
  },
  { label: __('Items List', 'bit-integrations'), key: 'items_list' },
  { label: __('Most Used', 'bit-integrations'), key: 'most_used' },
  { label: __('Back To Items', 'bit-integrations'), key: 'back_to_items' }
]

export const taxonomyFields = [
  { label: __('Slug', 'bit-integrations'), key: 'slug', required: true },
  { label: __('Singular Label', 'bit-integrations'), key: 'singular_label', required: true },
  { label: __('Plural Label', 'bit-integrations'), key: 'plural_label', required: true },
  { label: __('REST API base slug', 'bit-integrations'), key: 'rest_base', required: false },
  {
    label: __('REST API Controller Class', 'bit-integrations'),
    key: 'rest_controller_class',
    required: false
  },
  { label: __('Menu position', 'bit-integrations'), key: 'menu_position', required: false },
  { label: __('Capability type', 'bit-integrations'), key: 'capability_type', required: false },
  { label: __('Custom rewrite rules', 'bit-integrations'), key: 'custom_rewrite', required: false },
  { label: __('Custom query var', 'bit-integrations'), key: 'custom_query_var', required: false },
  { label: __('Default Term', 'bit-integrations'), key: 'default_term', required: false }
]

export const optionPageFields = [
  { label: __('Page Title', 'bit-integrations'), key: 'pageTitle', required: true },
  { label: __('Menu Title', 'bit-integrations'), key: 'menuTitle', required: true },
  { label: __('Menu Slug', 'bit-integrations'), key: 'menuSlug', required: true },
  { label: __('Menu Position', 'bit-integrations'), key: 'position', required: true },
  { label: __('Page Description', 'bit-integrations'), key: 'description', required: false }
]

export const supports = [
  { label: __('Title'), value: 'title' },
  { label: __('Editor'), value: 'editor' },
  { label: __('Comments'), value: 'comments' },
  { label: __('Revisions'), value: 'revisions' },
  { label: __('Trackbacks'), value: 'trackbacks' },
  { label: __('Author'), value: 'author' },
  { label: __('Excerpt'), value: 'excerpt' },
  { label: __('Page Attributes'), value: 'page-attributes' },
  { label: __('Thumbnail'), value: 'thumbnail' },
  { label: __('Custom Fields'), value: 'custom-fields' },
  { label: __('Post Formats'), value: 'post-formats' }
]

export const capabilities = [
  { label: __('Manage Terms'), value: 'manage_terms' },
  { label: __('Edit Terms'), value: 'edit_terms' },
  { label: __('Delete Terms'), value: 'delete_terms' },
  { label: __('Assign Terms'), value: 'assign_terms' }
]

export const cptIcons = [
  { label: 'Admin Appearance', value: 'admin-appearance' },
  { label: 'Admin Collapse', value: 'admin-collapse' },
  { label: 'Admin Comments', value: 'admin-comments' },
  { label: 'Admin Customizer', value: 'admin-customizer' },
  { label: 'Admin Generic', value: 'admin-generic' },
  { label: 'Admin Home', value: 'admin-home' },
  { label: 'Admin Links', value: 'admin-links' },
  { label: 'Admin Media', value: 'admin-media' },
  { label: 'Admin Multisite', value: 'admin-multisite' },
  { label: 'Admin Network', value: 'admin-network' },
  { label: 'Admin Page', value: 'admin-page' },
  { label: 'Admin Plugins', value: 'admin-plugins' },
  { label: 'Admin Post', value: 'admin-post' },
  { label: 'Admin Settings', value: 'admin-settings' },
  { label: 'Admin Site Alt', value: 'admin-site-alt' },
  { label: 'Admin Site Alt2', value: 'admin-site-alt2' },
  { label: 'Admin Site Alt3', value: 'admin-site-alt3' },
  { label: 'Admin Site', value: 'admin-site' },
  { label: 'Admin Tools', value: 'admin-tools' },
  { label: 'Admin Users', value: 'admin-users' },
  { label: 'Airplane', value: 'airplane' },
  { label: 'Album', value: 'album' },
  { label: 'Align Center', value: 'align-center' },
  { label: 'Align Full Width', value: 'align-full-width' },
  { label: 'Align Left', value: 'align-left' },
  { label: 'Align None', value: 'align-none' },
  { label: 'Align Pull Left', value: 'align-pull-left' },
  { label: 'Align Pull Right', value: 'align-pull-right' },
  { label: 'Align Right', value: 'align-right' },
  { label: 'Align Wide', value: 'align-wide' },
  { label: 'Amazon', value: 'amazon' },
  { label: 'Analytics', value: 'analytics' },
  { label: 'Archive', value: 'archive' },
  { label: 'Arrow Down Alt', value: 'arrow-down-alt' },
  { label: 'Arrow Down Alt2', value: 'arrow-down-alt2' },
  { label: 'Arrow Down', value: 'arrow-down' },
  { label: 'Arrow Left Alt', value: 'arrow-left-alt' },
  { label: 'Arrow Left Alt2', value: 'arrow-left-alt2' },
  { label: 'Arrow Left', value: 'arrow-left' },
  { label: 'Arrow Right Alt', value: 'arrow-right-alt' },
  { label: 'Arrow Right Alt2', value: 'arrow-right-alt2' },
  { label: 'Arrow Right', value: 'arrow-right' },
  { label: 'Arrow Up Alt', value: 'arrow-up-alt' },
  { label: 'Arrow Up Alt2', value: 'arrow-up-alt2' },
  { label: 'Arrow Up Duplicate', value: 'arrow-up-duplicate' },
  { label: 'Arrow Up', value: 'arrow-up' },
  { label: 'Art', value: 'art' },
  { label: 'Awards', value: 'awards' },
  { label: 'Backup', value: 'backup' },
  { label: 'Bank', value: 'bank' },
  { label: 'Beer', value: 'beer' },
  { label: 'Bell', value: 'bell' },
  { label: 'Block Default', value: 'block-default' },
  { label: 'Book Alt', value: 'book-alt' },
  { label: 'Book', value: 'book' },
  { label: 'Buddicons Activity', value: 'buddicons-activity' },
  { label: 'Buddicons Bbpress Logo', value: 'buddicons-bbpress-logo' },
  { label: 'Buddicons Buddypress Logo', value: 'buddicons-buddypress-logo' },
  { label: 'Buddicons Community', value: 'buddicons-community' },
  { label: 'Buddicons Forums', value: 'buddicons-forums' },
  { label: 'Buddicons Friends', value: 'buddicons-friends' },
  { label: 'Buddicons Groups', value: 'buddicons-groups' },
  { label: 'Buddicons Pm', value: 'buddicons-pm' },
  { label: 'Buddicons Replies', value: 'buddicons-replies' },
  { label: 'Buddicons Topics', value: 'buddicons-topics' },
  { label: 'Buddicons Tracking', value: 'buddicons-tracking' },
  { label: 'Building', value: 'building' },
  { label: 'Businessman', value: 'businessman' },
  { label: 'Businessperson', value: 'businessperson' },
  { label: 'Businesswoman', value: 'businesswoman' },
  { label: 'Button', value: 'button' },
  { label: 'Calculator', value: 'calculator' },
  { label: 'Calendar Alt', value: 'calendar-alt' },
  { label: 'Calendar', value: 'calendar' },
  { label: 'Camera Alt', value: 'camera-alt' },
  { label: 'Camera', value: 'camera' },
  { label: 'Car', value: 'car' },
  { label: 'Carrot', value: 'carrot' },
  { label: 'Cart', value: 'cart' },
  { label: 'Category', value: 'category' },
  { label: 'Chart Area', value: 'chart-area' },
  { label: 'Chart Bar', value: 'chart-bar' },
  { label: 'Chart Line', value: 'chart-line' },
  { label: 'Chart Pie', value: 'chart-pie' },
  { label: 'Clipboard', value: 'clipboard' },
  { label: 'Clock', value: 'clock' },
  { label: 'Cloud Saved', value: 'cloud-saved' },
  { label: 'Cloud Upload', value: 'cloud-upload' },
  { label: 'Cloud', value: 'cloud' },
  { label: 'Code Standards', value: 'code-standards' },
  { label: 'Coffee', value: 'coffee' },
  { label: 'Color Picker', value: 'color-picker' },
  { label: 'Columns', value: 'columns' },
  { label: 'Controls Back', value: 'controls-back' },
  { label: 'Controls Forward', value: 'controls-forward' },
  { label: 'Controls Pause', value: 'controls-pause' },
  { label: 'Controls Play', value: 'controls-play' },
  { label: 'Controls Repeat', value: 'controls-repeat' },
  { label: 'Controls Skipback', value: 'controls-skipback' },
  { label: 'Controls Skipforward', value: 'controls-skipforward' },
  { label: 'Controls Volumeoff', value: 'controls-volumeoff' },
  { label: 'Controls Volumeon', value: 'controls-volumeon' },
  { label: 'Cover Image', value: 'cover-image' },
  { label: 'Dashboard', value: 'dashboard' },
  { label: 'Database Add', value: 'database-add' },
  { label: 'Database Export', value: 'database-export' },
  { label: 'Database Import', value: 'database-import' },
  { label: 'Database Remove', value: 'database-remove' },
  { label: 'Database View', value: 'database-view' },
  { label: 'Database', value: 'database' },
  { label: 'Desktop', value: 'desktop' },
  { label: 'Dismiss', value: 'dismiss' },
  { label: 'Download', value: 'download' },
  { label: 'Drumstick', value: 'drumstick' },
  { label: 'Edit Large', value: 'edit-large' },
  { label: 'Edit Page', value: 'edit-page' },
  { label: 'Edit', value: 'edit' },
  { label: 'Editor Aligncenter', value: 'editor-aligncenter' },
  { label: 'Editor Alignleft', value: 'editor-alignleft' },
  { label: 'Editor Alignright', value: 'editor-alignright' },
  { label: 'Editor Bold', value: 'editor-bold' },
  { label: 'Editor Break', value: 'editor-break' },
  { label: 'Editor Code Duplicate', value: 'editor-code-duplicate' },
  { label: 'Editor Code', value: 'editor-code' },
  { label: 'Editor Contract', value: 'editor-contract' },
  { label: 'Editor Customchar', value: 'editor-customchar' },
  { label: 'Editor Expand', value: 'editor-expand' },
  { label: 'Editor Help', value: 'editor-help' },
  { label: 'Editor Indent', value: 'editor-indent' },
  { label: 'Editor Insertmore', value: 'editor-insertmore' },
  { label: 'Editor Italic', value: 'editor-italic' },
  { label: 'Editor Justify', value: 'editor-justify' },
  { label: 'Editor Kitchensink', value: 'editor-kitchensink' },
  { label: 'Editor Ltr', value: 'editor-ltr' },
  { label: 'Editor Ol Rtl', value: 'editor-ol-rtl' },
  { label: 'Editor Ol', value: 'editor-ol' },
  { label: 'Editor Outdent', value: 'editor-outdent' },
  { label: 'Editor Paragraph', value: 'editor-paragraph' },
  { label: 'Editor Paste Text', value: 'editor-paste-text' },
  { label: 'Editor Paste Word', value: 'editor-paste-word' },
  { label: 'Editor Quote', value: 'editor-quote' },
  { label: 'Editor Removeformatting', value: 'editor-removeformatting' },
  { label: 'Editor Rtl', value: 'editor-rtl' },
  { label: 'Editor Spellcheck', value: 'editor-spellcheck' },
  { label: 'Editor Strikethrough', value: 'editor-strikethrough' },
  { label: 'Editor Table', value: 'editor-table' },
  { label: 'Editor Textcolor', value: 'editor-textcolor' },
  { label: 'Editor Ul', value: 'editor-ul' },
  { label: 'Editor Underline', value: 'editor-underline' },
  { label: 'Editor Unlink', value: 'editor-unlink' },
  { label: 'Editor Video', value: 'editor-video' },
  { label: 'Ellipsis', value: 'ellipsis' },
  { label: 'Email Alt', value: 'email-alt' },
  { label: 'Email Alt2', value: 'email-alt2' },
  { label: 'Email', value: 'email' },
  { label: 'Embed Audio', value: 'embed-audio' },
  { label: 'Embed Generic', value: 'embed-generic' },
  { label: 'Embed Photo', value: 'embed-photo' },
  { label: 'Embed Post', value: 'embed-post' },
  { label: 'Embed Video', value: 'embed-video' },
  { label: 'Excerpt View', value: 'excerpt-view' },
  { label: 'Exit', value: 'exit' },
  { label: 'External', value: 'external' },
  { label: 'Facebook Alt', value: 'facebook-alt' },
  { label: 'Facebook', value: 'facebook' },
  { label: 'Feedback', value: 'feedback' },
  { label: 'Filter', value: 'filter' },
  { label: 'Flag', value: 'flag' },
  { label: 'Food', value: 'food' },
  { label: 'Format Aside', value: 'format-aside' },
  { label: 'Format Audio', value: 'format-audio' },
  { label: 'Format Chat', value: 'format-chat' },
  { label: 'Format Gallery', value: 'format-gallery' },
  { label: 'Format Image', value: 'format-image' },
  { label: 'Format Quote', value: 'format-quote' },
  { label: 'Format Status', value: 'format-status' },
  { label: 'Format Video', value: 'format-video' },
  { label: 'Forms', value: 'forms' },
  { label: 'Fullscreen Alt', value: 'fullscreen-alt' },
  { label: 'Fullscreen Exit Alt', value: 'fullscreen-exit-alt' },
  { label: 'Games', value: 'games' },
  { label: 'Google', value: 'google' },
  { label: 'Googleplus', value: 'googleplus' },
  { label: 'Grid View', value: 'grid-view' },
  { label: 'Groups', value: 'groups' },
  { label: 'Hammer', value: 'hammer' },
  { label: 'Heading', value: 'heading' },
  { label: 'Heart', value: 'heart' },
  { label: 'Hidden', value: 'hidden' },
  { label: 'Hourglass', value: 'hourglass' },
  { label: 'Html', value: 'html' },
  { label: 'Id Alt', value: 'id-alt' },
  { label: 'Id', value: 'id' },
  { label: 'Image Crop', value: 'image-crop' },
  { label: 'Image Filter', value: 'image-filter' },
  { label: 'Image Flip Horizontal', value: 'image-flip-horizontal' },
  { label: 'Image Flip Vertical', value: 'image-flip-vertical' },
  { label: 'Image Rotate Left', value: 'image-rotate-left' },
  { label: 'Image Rotate Right', value: 'image-rotate-right' },
  { label: 'Image Rotate', value: 'image-rotate' },
  { label: 'Images Alt', value: 'images-alt' },
  { label: 'Images Alt2', value: 'images-alt2' },
  { label: 'Index Card', value: 'index-card' },
  { label: 'Info Outline', value: 'info-outline' },
  { label: 'Info', value: 'info' },
  { label: 'Insert After', value: 'insert-after' },
  { label: 'Insert Before', value: 'insert-before' },
  { label: 'Insert', value: 'insert' },
  { label: 'Instagram', value: 'instagram' },
  { label: 'Laptop', value: 'laptop' },
  { label: 'Layout', value: 'layout' },
  { label: 'Leftright', value: 'leftright' },
  { label: 'Lightbulb', value: 'lightbulb' },
  { label: 'Linkedin', value: 'linkedin' },
  { label: 'List View', value: 'list-view' },
  { label: 'Location Alt', value: 'location-alt' },
  { label: 'Location', value: 'location' },
  { label: 'Lock Duplicate', value: 'lock-duplicate' },
  { label: 'Lock', value: 'lock' },
  { label: 'Marker', value: 'marker' },
  { label: 'Media Archive', value: 'media-archive' },
  { label: 'Media Audio', value: 'media-audio' },
  { label: 'Media Code', value: 'media-code' },
  { label: 'Media Default', value: 'media-default' },
  { label: 'Media Document', value: 'media-document' },
  { label: 'Media Interactive', value: 'media-interactive' },
  { label: 'Media Spreadsheet', value: 'media-spreadsheet' },
  { label: 'Media Text', value: 'media-text' },
  { label: 'Media Video', value: 'media-video' },
  { label: 'Megaphone', value: 'megaphone' },
  { label: 'Menu Alt', value: 'menu-alt' },
  { label: 'Menu Alt2', value: 'menu-alt2' },
  { label: 'Menu Alt3', value: 'menu-alt3' },
  { label: 'Menu', value: 'menu' },
  { label: 'Microphone', value: 'microphone' },
  { label: 'Migrate', value: 'migrate' },
  { label: 'Minus', value: 'minus' },
  { label: 'Money Alt', value: 'money-alt' },
  { label: 'Money', value: 'money' },
  { label: 'Move', value: 'move' },
  { label: 'Nametag', value: 'nametag' },
  { label: 'Networking', value: 'networking' },
  { label: 'No Alt', value: 'no-alt' },
  { label: 'No', value: 'no' },
  { label: 'Open Folder', value: 'open-folder' },
  { label: 'Palmtree', value: 'palmtree' },
  { label: 'Paperclip', value: 'paperclip' },
  { label: 'Pdf', value: 'pdf' },
  { label: 'Performance', value: 'performance' },
  { label: 'Pets', value: 'pets' },
  { label: 'Phone', value: 'phone' },
  { label: 'Pinterest', value: 'pinterest' },
  { label: 'Playlist Audio', value: 'playlist-audio' },
  { label: 'Playlist Video', value: 'playlist-video' },
  { label: 'Plugins Checked', value: 'plugins-checked' },
  { label: 'Plus Alt', value: 'plus-alt' },
  { label: 'Plus Alt2', value: 'plus-alt2' },
  { label: 'Plus', value: 'plus' },
  { label: 'Podio', value: 'podio' },
  { label: 'Portfolio', value: 'portfolio' },
  { label: 'Post Status', value: 'post-status' },
  { label: 'Pressthis', value: 'pressthis' },
  { label: 'Printer', value: 'printer' },
  { label: 'Privacy', value: 'privacy' },
  { label: 'Products', value: 'products' },
  { label: 'Randomize', value: 'randomize' },
  { label: 'Reddit', value: 'reddit' },
  { label: 'Redo', value: 'redo' },
  { label: 'Remove', value: 'remove' },
  { label: 'Rest Api', value: 'rest-api' },
  { label: 'Rss', value: 'rss' },
  { label: 'Saved', value: 'saved' },
  { label: 'Schedule', value: 'schedule' },
  { label: 'Screenoptions', value: 'screenoptions' },
  { label: 'Search', value: 'search' },
  { label: 'Share Alt', value: 'share-alt' },
  { label: 'Share Alt2', value: 'share-alt2' },
  { label: 'Share', value: 'share' },
  { label: 'Shield Alt', value: 'shield-alt' },
  { label: 'Shield', value: 'shield' },
  { label: 'Shortcode', value: 'shortcode' },
  { label: 'Slides', value: 'slides' },
  { label: 'Smartphone', value: 'smartphone' },
  { label: 'Smiley', value: 'smiley' },
  { label: 'Sort', value: 'sort' },
  { label: 'Sos', value: 'sos' },
  { label: 'Spotify', value: 'spotify' },
  { label: 'Star Empty', value: 'star-empty' },
  { label: 'Star Filled', value: 'star-filled' },
  { label: 'Star Half', value: 'star-half' },
  { label: 'Sticky', value: 'sticky' },
  { label: 'Store', value: 'store' },
  { label: 'Superhero Alt', value: 'superhero-alt' },
  { label: 'Superhero', value: 'superhero' },
  { label: 'Table Col After', value: 'table-col-after' },
  { label: 'Table Col Before', value: 'table-col-before' },
  { label: 'Table Col Delete', value: 'table-col-delete' },
  { label: 'Table Row After', value: 'table-row-after' },
  { label: 'Table Row Before', value: 'table-row-before' },
  { label: 'Table Row Delete', value: 'table-row-delete' },
  { label: 'Tablet', value: 'tablet' },
  { label: 'Tag', value: 'tag' },
  { label: 'Tagcloud', value: 'tagcloud' },
  { label: 'Testimonial', value: 'testimonial' },
  { label: 'Text Page', value: 'text-page' },
  { label: 'Text', value: 'text' },
  { label: 'Thumbs Down', value: 'thumbs-down' },
  { label: 'Thumbs Up', value: 'thumbs-up' },
  { label: 'Tickets Alt', value: 'tickets-alt' },
  { label: 'Tickets', value: 'tickets' },
  { label: 'Tide', value: 'tide' },
  { label: 'Translation', value: 'translation' },
  { label: 'Trash', value: 'trash' },
  { label: 'Twitch', value: 'twitch' },
  { label: 'Twitter Alt', value: 'twitter-alt' },
  { label: 'Twitter', value: 'twitter' },
  { label: 'Undo', value: 'undo' },
  { label: 'Universal Access Alt', value: 'universal-access-alt' },
  { label: 'Universal Access', value: 'universal-access' },
  { label: 'Unlock', value: 'unlock' },
  { label: 'Update Alt', value: 'update-alt' },
  { label: 'Update', value: 'update' },
  { label: 'Upload', value: 'upload' },
  { label: 'Vault', value: 'vault' },
  { label: 'Video Alt', value: 'video-alt' },
  { label: 'Video Alt2', value: 'video-alt2' },
  { label: 'Video Alt3', value: 'video-alt3' },
  { label: 'Visibility', value: 'visibility' },
  { label: 'Warning', value: 'warning' },
  { label: 'Welcome Add Page', value: 'welcome-add-page' },
  { label: 'Welcome Comments', value: 'welcome-comments' },
  { label: 'Welcome Learn More', value: 'welcome-learn-more' },
  { label: 'Welcome View Site', value: 'welcome-view-site' },
  { label: 'Welcome Widgets Menus', value: 'welcome-widgets-menus' },
  { label: 'Welcome Write Blog', value: 'welcome-write-blog' },
  { label: 'Whatsapp', value: 'whatsapp' },
  { label: 'Wordpress Alt', value: 'wordpress-alt' },
  { label: 'Wordpress', value: 'wordpress' },
  { label: 'Xing', value: 'xing' },
  { label: 'Yes Alt', value: 'yes-alt' },
  { label: 'Yes', value: 'yes' },
  { label: 'Youtube', value: 'youtube' }
]

export const optionPageCapabilities = [
  { label: 'Moderate Comments', value: 'moderate_comments' },
  { label: 'Manage Options', value: 'manage_options' },
  { label: 'Manage Categories', value: 'manage_categories' },
  { label: 'Manage Links', value: 'manage_links' },
  { label: 'Unfiltered HTML', value: 'unfiltered_html' },
  { label: "Edit Others' Posts", value: 'edit_others_posts' },
  { label: 'Edit Pages', value: 'edit_pages' },
  { label: "Edit Others' Pages", value: 'edit_others_pages' },
  { label: 'Edit Published Pages', value: 'edit_published_pages' },
  { label: 'Publish Pages', value: 'publish_pages' },
  { label: 'Delete Pages', value: 'delete_pages' },
  { label: "Delete Others' Pages", value: 'delete_others_pages' },
  { label: 'Delete Published Pages', value: 'delete_published_pages' },
  { label: "Delete Others' Posts", value: 'delete_others_posts' },
  { label: 'Delete Private Posts', value: 'delete_private_posts' },
  { label: 'Edit Private Posts', value: 'edit_private_posts' },
  { label: 'Read Private Posts', value: 'read_private_posts' },
  { label: 'Delete Private Pages', value: 'delete_private_pages' },
  { label: 'Edit Private Pages', value: 'edit_private_pages' },
  { label: 'Read Private Pages', value: 'read_private_pages' }
]
