import { __ } from '../../../Utils/i18nwrap'

export const modules = [
  { name: 'create_cpt', label: __('Create CPT', 'bit-integrations'), is_pro: false },
  { name: 'update_cpt', label: __('Update CPT', 'bit-integrations'), is_pro: true },
  { name: 'delete_cpt', label: __('Delete CPT', 'bit-integrations'), is_pro: true },
  { name: 'create_taxonomy', label: __('Create Taxonomy', 'bit-integrations'), is_pro: true },
  { name: 'update_taxonomy', label: __('Update Taxonomy', 'bit-integrations'), is_pro: true },
  { name: 'delete_taxonomy', label: __('Delete Taxonomy', 'bit-integrations'), is_pro: true },
  {
    name: 'associate_taxonomy_to_cpt',
    label: __('Associate Taxonomy To CPT', 'bit-integrations'),
    is_pro: true
  },
  { name: 'create_option_page', label: __('Create Option Page', 'bit-integrations'), is_pro: true },
  { name: 'update_option_page', label: __('Update Option Page', 'bit-integrations'), is_pro: true },
  { name: 'delete_option_page', label: __('Delete Option Page', 'bit-integrations'), is_pro: true },
  { name: 'delete_meta_group', label: __('Delete Meta Field Group', 'bit-integrations'), is_pro: true },
  { name: 'delete_dynamic_block', label: __('Delete Dynamic Block', 'bit-integrations'), is_pro: true }
]

export const cptFields = [
  { label: __('Post Name', 'bit-integrations'), key: 'post_name', required: true },
  { label: __('Singular Label', 'bit-integrations'), key: 'singular_label', required: true },
  { label: __('Plural Label', 'bit-integrations'), key: 'plural_label', required: true },
  { label: __('REST API base slug', 'bit-integrations'), key: 'rest_base', required: false },
  { label: __('Menu position', 'bit-integrations'), key: 'menu_position', required: false },
  { label: __('Capability type', 'bit-integrations'), key: 'capability_type', required: false },
  { label: __('Custom rewrite rules', 'bit-integrations'), key: 'custom_rewrite', required: false },
  { label: __('Custom query var', 'bit-integrations'), key: 'custom_query_var', required: false }
]

export const cptLabels = [
  { label: __('Menu Name', 'bit-integrations'), key: 'menu_name' },
  { label: __('All Items', 'bit-integrations'), key: 'all_items' },
  { label: __('Add New', 'bit-integrations'), key: 'add_new' },
  { label: __('Add New Item', 'bit-integrations'), key: 'add_new_item' },
  { label: __('Edit Item', 'bit-integrations'), key: 'edit_item' },
  { label: __('New Item', 'bit-integrations'), key: 'new_item' },
  { label: __('View Item', 'bit-integrations'), key: 'view_item' },
  { label: __('View Items', 'bit-integrations'), key: 'view_items' },
  { label: __('Search Item', 'bit-integrations'), key: 'search_item' },
  { label: __('Not Found', 'bit-integrations'), key: 'not_found' },
  { label: __('Not Found in Trash', 'bit-integrations'), key: 'not_found_in_trash' },
  { label: __('Parent Item Colon', 'bit-integrations'), key: 'parent_item_colon' },
  { label: __('Featured Image', 'bit-integrations'), key: 'featured_image' },
  { label: __('Set Featured Image', 'bit-integrations'), key: 'set_featured_image' },
  { label: __('Remove Featured Image', 'bit-integrations'), key: 'remove_featured_image' },
  { label: __('Use Featured Image', 'bit-integrations'), key: 'use_featured_image' },
  { label: __('Archives', 'bit-integrations'), key: 'archives' },
  { label: __('Insert into Item', 'bit-integrations'), key: 'insert_into_item' },
  { label: __('Uploaded to This Item', 'bit-integrations'), key: 'uploaded_to_this_item' },
  { label: __('Filter Items List', 'bit-integrations'), key: 'filter_items_list' },
  { label: __('Items List Navigation', 'bit-integrations'), key: 'items_list_navigation' },
  { label: __('Items List', 'bit-integrations'), key: 'items_list' },
  { label: __('Filter by Date', 'bit-integrations'), key: 'filter_by_date' },
  { label: __('Item Published', 'bit-integrations'), key: 'item_published' },
  { label: __('Item Published Privately', 'bit-integrations'), key: 'item_published_privately' },
  { label: __('Item Reverted to Draft', 'bit-integrations'), key: 'item_reverted_to_draft' },
  { label: __('Item Scheduled', 'bit-integrations'), key: 'item_scheduled' },
  { label: __('Item Updated', 'bit-integrations'), key: 'item_updated' }
]

export const taxonomyLabels = [
  { label: __('Menu Name', 'bit-integrations'), key: 'name' },
  { label: __('Singular name', 'bit-integrations'), key: 'singular_name' },
  { label: __('Search Items', 'bit-integrations'), key: 'search_items' },
  { label: __('Popular Items', 'bit-integrations'), key: 'popular_items' },
  { label: __('All Items', 'bit-integrations'), key: 'all_items' },
  { label: __('Parent Item', 'bit-integrations'), key: 'parent_item' },
  { label: __('Parent Item Colon', 'bit-integrations'), key: 'parent_item_colon' },
  { label: __('Edit Item', 'bit-integrations'), key: 'edit_item' },
  { label: __('View Item', 'bit-integrations'), key: 'view_item' },
  { label: __('Update Item', 'bit-integrations'), key: 'update_item' },
  { label: __('Add New Item', 'bit-integrations'), key: 'add_new_item' },
  { label: __('New Item Name', 'bit-integrations'), key: 'new_item_name' },
  {
    label: __('Separate Items With Commas', 'bit-integrations'),
    key: 'separate_items_with_commas'
  },
  { label: __('Add or Remove Items', 'bit-integrations'), key: 'add_or_remove_items' },
  {
    label: __('Choose From Most Used', 'bit-integrations'),
    key: 'choose_from_most_used'
  },
  { label: __('Not Found', 'bit-integrations'), key: 'not_found' },
  { label: __('No Terms', 'bit-integrations'), key: 'no_terms' },
  { label: __('Filter By Item', 'bit-integrations'), key: 'filter_by_item' },
  {
    label: __('Items List Navigation', 'bit-integrations'),
    key: 'items_list_navigation'
  },
  { label: __('Items List', 'bit-integrations'), key: 'items_list' },
  { label: __('Most Used', 'bit-integrations'), key: 'most_used' },
  { label: __('Back To Items', 'bit-integrations'), key: 'back_to_items' }
]

export const taxonomyFields = [
  { label: __('Slug', 'bit-integrations'), key: 'slug', required: true },
  { label: __('Singular Label', 'bit-integrations'), key: 'singular_label', required: true },
  { label: __('Plural Label', 'bit-integrations'), key: 'plural_label', required: true },
  { label: __('REST API base slug', 'bit-integrations'), key: 'rest_base', required: false },
  {
    label: __('REST API Controller Class', 'bit-integrations'),
    key: 'rest_controller_class',
    required: false
  },
  { label: __('Menu position', 'bit-integrations'), key: 'menu_position', required: false },
  { label: __('Capability type', 'bit-integrations'), key: 'capability_type', required: false },
  { label: __('Custom rewrite rules', 'bit-integrations'), key: 'custom_rewrite', required: false },
  { label: __('Custom query var', 'bit-integrations'), key: 'custom_query_var', required: false },
  { label: __('Default Term', 'bit-integrations'), key: 'default_term', required: false }
]

export const optionPageFields = [
  { label: __('Page Title', 'bit-integrations'), key: 'pageTitle', required: true },
  { label: __('Menu Title', 'bit-integrations'), key: 'menuTitle', required: true },
  { label: __('Menu Slug', 'bit-integrations'), key: 'menuSlug', required: true },
  { label: __('Menu Position', 'bit-integrations'), key: 'position', required: true },
  { label: __('Capability', 'bit-integrations'), key: 'capability', required: true },
  { label: __('Page Description', 'bit-integrations'), key: 'description', required: false }
]

export const supports = [
  { label: __('Title'), value: 'title' },
  { label: __('Editor'), value: 'editor' },
  { label: __('Comments'), value: 'comments' },
  { label: __('Revisions'), value: 'revisions' },
  { label: __('Trackbacks'), value: 'trackbacks' },
  { label: __('Author'), value: 'author' },
  { label: __('Excerpt'), value: 'excerpt' },
  { label: __('Page Attributes'), value: 'page-attributes' },
  { label: __('Thumbnail'), value: 'thumbnail' },
  { label: __('Custom Fields'), value: 'custom-fields' },
  { label: __('Post Formats'), value: 'post-formats' }
]

export const capabilities = [
  { label: __('Manage Terms'), value: 'manage_terms' },
  { label: __('Edit Terms'), value: 'edit_terms' },
  { label: __('Delete Terms'), value: 'delete_terms' },
  { label: __('Assign Terms'), value: 'assign_terms' }
]

export const cptIcons = [
  { label: 'admin-appearance', value: 'admin-appearance' },
  { label: 'admin-collapse', value: 'admin-collapse' },
  { label: 'admin-comments', value: 'admin-comments' },
  { label: 'admin-customizer', value: 'admin-customizer' },
  { label: 'admin-generic', value: 'admin-generic' },
  { label: 'admin-home', value: 'admin-home' },
  { label: 'admin-links', value: 'admin-links' },
  { label: 'admin-media', value: 'admin-media' },
  { label: 'admin-multisite', value: 'admin-multisite' },
  { label: 'admin-network', value: 'admin-network' },
  { label: 'admin-page', value: 'admin-page' },
  { label: 'admin-plugins', value: 'admin-plugins' },
  { label: 'admin-post', value: 'admin-post' },
  { label: 'admin-settings', value: 'admin-settings' },
  { label: 'admin-site-alt', value: 'admin-site-alt' },
  { label: 'admin-site-alt2', value: 'admin-site-alt2' },
  { label: 'admin-site-alt3', value: 'admin-site-alt3' },
  { label: 'admin-site', value: 'admin-site' },
  { label: 'admin-tools', value: 'admin-tools' },
  { label: 'admin-users', value: 'admin-users' },
  { label: 'airplane', value: 'airplane' },
  { label: 'album', value: 'album' },
  { label: 'align-center', value: 'align-center' },
  { label: 'align-full-width', value: 'align-full-width' },
  { label: 'align-left', value: 'align-left' },
  { label: 'align-none', value: 'align-none' },
  { label: 'align-pull-left', value: 'align-pull-left' },
  { label: 'align-pull-right', value: 'align-pull-right' },
  { label: 'align-right', value: 'align-right' },
  { label: 'align-wide', value: 'align-wide' },
  { label: 'amazon', value: 'amazon' },
  { label: 'analytics', value: 'analytics' },
  { label: 'archive', value: 'archive' },
  { label: 'arrow-down-alt', value: 'arrow-down-alt' },
  { label: 'arrow-down-alt2', value: 'arrow-down-alt2' },
  { label: 'arrow-down', value: 'arrow-down' },
  { label: 'arrow-left-alt', value: 'arrow-left-alt' },
  { label: 'arrow-left-alt2', value: 'arrow-left-alt2' },
  { label: 'arrow-left', value: 'arrow-left' },
  { label: 'arrow-right-alt', value: 'arrow-right-alt' },
  { label: 'arrow-right-alt2', value: 'arrow-right-alt2' },
  { label: 'arrow-right', value: 'arrow-right' },
  { label: 'arrow-up-alt', value: 'arrow-up-alt' },
  { label: 'arrow-up-alt2', value: 'arrow-up-alt2' },
  { label: 'arrow-up-duplicate', value: 'arrow-up-duplicate' },
  { label: 'arrow-up', value: 'arrow-up' },
  { label: 'art', value: 'art' },
  { label: 'awards', value: 'awards' },
  { label: 'backup', value: 'backup' },
  { label: 'bank', value: 'bank' },
  { label: 'beer', value: 'beer' },
  { label: 'bell', value: 'bell' },
  { label: 'block-default', value: 'block-default' },
  { label: 'book-alt', value: 'book-alt' },
  { label: 'book', value: 'book' },
  { label: 'buddicons-activity', value: 'buddicons-activity' },
  { label: 'buddicons-bbpress-logo', value: 'buddicons-bbpress-logo' },
  { label: 'buddicons-buddypress-logo', value: 'buddicons-buddypress-logo' },
  { label: 'buddicons-community', value: 'buddicons-community' },
  { label: 'buddicons-forums', value: 'buddicons-forums' },
  { label: 'buddicons-friends', value: 'buddicons-friends' },
  { label: 'buddicons-groups', value: 'buddicons-groups' },
  { label: 'buddicons-pm', value: 'buddicons-pm' },
  { label: 'buddicons-replies', value: 'buddicons-replies' },
  { label: 'buddicons-topics', value: 'buddicons-topics' },
  { label: 'buddicons-tracking', value: 'buddicons-tracking' },
  { label: 'building', value: 'building' },
  { label: 'businessman', value: 'businessman' },
  { label: 'businessperson', value: 'businessperson' },
  { label: 'businesswoman', value: 'businesswoman' },
  { label: 'button', value: 'button' },
  { label: 'calculator', value: 'calculator' },
  { label: 'calendar-alt', value: 'calendar-alt' },
  { label: 'calendar', value: 'calendar' },
  { label: 'camera-alt', value: 'camera-alt' },
  { label: 'camera', value: 'camera' },
  { label: 'car', value: 'car' },
  { label: 'carrot', value: 'carrot' },
  { label: 'cart', value: 'cart' },
  { label: 'category', value: 'category' },
  { label: 'chart-area', value: 'chart-area' },
  { label: 'chart-bar', value: 'chart-bar' },
  { label: 'chart-line', value: 'chart-line' },
  { label: 'chart-pie', value: 'chart-pie' },
  { label: 'clipboard', value: 'clipboard' },
  { label: 'clock', value: 'clock' },
  { label: 'cloud-saved', value: 'cloud-saved' },
  { label: 'cloud-upload', value: 'cloud-upload' },
  { label: 'cloud', value: 'cloud' },
  { label: 'code-standards', value: 'code-standards' },
  { label: 'coffee', value: 'coffee' },
  { label: 'color-picker', value: 'color-picker' },
  { label: 'columns', value: 'columns' },
  { label: 'controls-back', value: 'controls-back' },
  { label: 'controls-forward', value: 'controls-forward' },
  { label: 'controls-pause', value: 'controls-pause' },
  { label: 'controls-play', value: 'controls-play' },
  { label: 'controls-repeat', value: 'controls-repeat' },
  { label: 'controls-skipback', value: 'controls-skipback' },
  { label: 'controls-skipforward', value: 'controls-skipforward' },
  { label: 'controls-volumeoff', value: 'controls-volumeoff' },
  { label: 'controls-volumeon', value: 'controls-volumeon' },
  { label: 'cover-image', value: 'cover-image' },
  { label: 'dashboard', value: 'dashboard' },
  { label: 'database-add', value: 'database-add' },
  { label: 'database-export', value: 'database-export' },
  { label: 'database-import', value: 'database-import' },
  { label: 'database-remove', value: 'database-remove' },
  { label: 'database-view', value: 'database-view' },
  { label: 'database', value: 'database' },
  { label: 'desktop', value: 'desktop' },
  { label: 'dismiss', value: 'dismiss' },
  { label: 'download', value: 'download' },
  { label: 'drumstick', value: 'drumstick' },
  { label: 'edit-large', value: 'edit-large' },
  { label: 'edit-page', value: 'edit-page' },
  { label: 'edit', value: 'edit' },
  { label: 'editor-aligncenter', value: 'editor-aligncenter' },
  { label: 'editor-alignleft', value: 'editor-alignleft' },
  { label: 'editor-alignright', value: 'editor-alignright' },
  { label: 'editor-bold', value: 'editor-bold' },
  { label: 'editor-break', value: 'editor-break' },
  { label: 'editor-code-duplicate', value: 'editor-code-duplicate' },
  { label: 'editor-code', value: 'editor-code' },
  { label: 'editor-contract', value: 'editor-contract' },
  { label: 'editor-customchar', value: 'editor-customchar' },
  { label: 'editor-expand', value: 'editor-expand' },
  { label: 'editor-help', value: 'editor-help' },
  { label: 'editor-indent', value: 'editor-indent' },
  { label: 'editor-insertmore', value: 'editor-insertmore' },
  { label: 'editor-italic', value: 'editor-italic' },
  { label: 'editor-justify', value: 'editor-justify' },
  { label: 'editor-kitchensink', value: 'editor-kitchensink' },
  { label: 'editor-ltr', value: 'editor-ltr' },
  { label: 'editor-ol-rtl', value: 'editor-ol-rtl' },
  { label: 'editor-ol', value: 'editor-ol' },
  { label: 'editor-outdent', value: 'editor-outdent' },
  { label: 'editor-paragraph', value: 'editor-paragraph' },
  { label: 'editor-paste-text', value: 'editor-paste-text' },
  { label: 'editor-paste-word', value: 'editor-paste-word' },
  { label: 'editor-quote', value: 'editor-quote' },
  { label: 'editor-removeformatting', value: 'editor-removeformatting' },
  { label: 'editor-rtl', value: 'editor-rtl' },
  { label: 'editor-spellcheck', value: 'editor-spellcheck' },
  { label: 'editor-strikethrough', value: 'editor-strikethrough' },
  { label: 'editor-table', value: 'editor-table' },
  { label: 'editor-textcolor', value: 'editor-textcolor' },
  { label: 'editor-ul', value: 'editor-ul' },
  { label: 'editor-underline', value: 'editor-underline' },
  { label: 'editor-unlink', value: 'editor-unlink' },
  { label: 'editor-video', value: 'editor-video' },
  { label: 'ellipsis', value: 'ellipsis' },
  { label: 'email-alt', value: 'email-alt' },
  { label: 'email-alt2', value: 'email-alt2' },
  { label: 'email', value: 'email' },
  { label: 'embed-audio', value: 'embed-audio' },
  { label: 'embed-generic', value: 'embed-generic' },
  { label: 'embed-photo', value: 'embed-photo' },
  { label: 'embed-post', value: 'embed-post' },
  { label: 'embed-video', value: 'embed-video' },
  { label: 'excerpt-view', value: 'excerpt-view' },
  { label: 'exit', value: 'exit' },
  { label: 'external', value: 'external' },
  { label: 'facebook-alt', value: 'facebook-alt' },
  { label: 'facebook', value: 'facebook' },
  { label: 'feedback', value: 'feedback' },
  { label: 'filter', value: 'filter' },
  { label: 'flag', value: 'flag' },
  { label: 'food', value: 'food' },
  { label: 'format-aside', value: 'format-aside' },
  { label: 'format-audio', value: 'format-audio' },
  { label: 'format-chat', value: 'format-chat' },
  { label: 'format-gallery', value: 'format-gallery' },
  { label: 'format-image', value: 'format-image' },
  { label: 'format-quote', value: 'format-quote' },
  { label: 'format-status', value: 'format-status' },
  { label: 'format-video', value: 'format-video' },
  { label: 'forms', value: 'forms' },
  { label: 'fullscreen-alt', value: 'fullscreen-alt' },
  { label: 'fullscreen-exit-alt', value: 'fullscreen-exit-alt' },
  { label: 'games', value: 'games' },
  { label: 'google', value: 'google' },
  { label: 'googleplus', value: 'googleplus' },
  { label: 'grid-view', value: 'grid-view' },
  { label: 'groups', value: 'groups' },
  { label: 'hammer', value: 'hammer' },
  { label: 'heading', value: 'heading' },
  { label: 'heart', value: 'heart' },
  { label: 'hidden', value: 'hidden' },
  { label: 'hourglass', value: 'hourglass' },
  { label: 'html', value: 'html' },
  { label: 'id-alt', value: 'id-alt' },
  { label: 'id', value: 'id' },
  { label: 'image-crop', value: 'image-crop' },
  { label: 'image-filter', value: 'image-filter' },
  { label: 'image-flip-horizontal', value: 'image-flip-horizontal' },
  { label: 'image-flip-vertical', value: 'image-flip-vertical' },
  { label: 'image-rotate-left', value: 'image-rotate-left' },
  { label: 'image-rotate-right', value: 'image-rotate-right' },
  { label: 'image-rotate', value: 'image-rotate' },
  { label: 'images-alt', value: 'images-alt' },
  { label: 'images-alt2', value: 'images-alt2' },
  { label: 'index-card', value: 'index-card' },
  { label: 'info-outline', value: 'info-outline' },
  { label: 'info', value: 'info' },
  { label: 'insert-after', value: 'insert-after' },
  { label: 'insert-before', value: 'insert-before' },
  { label: 'insert', value: 'insert' },
  { label: 'instagram', value: 'instagram' },
  { label: 'laptop', value: 'laptop' },
  { label: 'layout', value: 'layout' },
  { label: 'leftright', value: 'leftright' },
  { label: 'lightbulb', value: 'lightbulb' },
  { label: 'linkedin', value: 'linkedin' },
  { label: 'list-view', value: 'list-view' },
  { label: 'location-alt', value: 'location-alt' },
  { label: 'location', value: 'location' },
  { label: 'lock-duplicate', value: 'lock-duplicate' },
  { label: 'lock', value: 'lock' },
  { label: 'marker', value: 'marker' },
  { label: 'media-archive', value: 'media-archive' },
  { label: 'media-audio', value: 'media-audio' },
  { label: 'media-code', value: 'media-code' },
  { label: 'media-default', value: 'media-default' },
  { label: 'media-document', value: 'media-document' },
  { label: 'media-interactive', value: 'media-interactive' },
  { label: 'media-spreadsheet', value: 'media-spreadsheet' },
  { label: 'media-text', value: 'media-text' },
  { label: 'media-video', value: 'media-video' },
  { label: 'megaphone', value: 'megaphone' },
  { label: 'menu-alt', value: 'menu-alt' },
  { label: 'menu-alt2', value: 'menu-alt2' },
  { label: 'menu-alt3', value: 'menu-alt3' },
  { label: 'menu', value: 'menu' },
  { label: 'microphone', value: 'microphone' },
  { label: 'migrate', value: 'migrate' },
  { label: 'minus', value: 'minus' },
  { label: 'money-alt', value: 'money-alt' },
  { label: 'money', value: 'money' },
  { label: 'move', value: 'move' },
  { label: 'nametag', value: 'nametag' },
  { label: 'networking', value: 'networking' },
  { label: 'no-alt', value: 'no-alt' },
  { label: 'no', value: 'no' },
  { label: 'open-folder', value: 'open-folder' },
  { label: 'palmtree', value: 'palmtree' },
  { label: 'paperclip', value: 'paperclip' },
  { label: 'pdf', value: 'pdf' },
  { label: 'performance', value: 'performance' },
  { label: 'pets', value: 'pets' },
  { label: 'phone', value: 'phone' },
  { label: 'pinterest', value: 'pinterest' },
  { label: 'playlist-audio', value: 'playlist-audio' },
  { label: 'playlist-video', value: 'playlist-video' },
  { label: 'plugins-checked', value: 'plugins-checked' },
  { label: 'plus-alt', value: 'plus-alt' },
  { label: 'plus-alt2', value: 'plus-alt2' },
  { label: 'plus', value: 'plus' },
  { label: 'podio', value: 'podio' },
  { label: 'portfolio', value: 'portfolio' },
  { label: 'post-status', value: 'post-status' },
  { label: 'pressthis', value: 'pressthis' },
  { label: 'printer', value: 'printer' },
  { label: 'privacy', value: 'privacy' },
  { label: 'products', value: 'products' },
  { label: 'randomize', value: 'randomize' },
  { label: 'reddit', value: 'reddit' },
  { label: 'redo', value: 'redo' },
  { label: 'remove', value: 'remove' },
  { label: 'rest-api', value: 'rest-api' },
  { label: 'rss', value: 'rss' },
  { label: 'saved', value: 'saved' },
  { label: 'schedule', value: 'schedule' },
  { label: 'screenoptions', value: 'screenoptions' },
  { label: 'search', value: 'search' },
  { label: 'share-alt', value: 'share-alt' },
  { label: 'share-alt2', value: 'share-alt2' },
  { label: 'share', value: 'share' },
  { label: 'shield-alt', value: 'shield-alt' },
  { label: 'shield', value: 'shield' },
  { label: 'shortcode', value: 'shortcode' },
  { label: 'slides', value: 'slides' },
  { label: 'smartphone', value: 'smartphone' },
  { label: 'smiley', value: 'smiley' },
  { label: 'sort', value: 'sort' },
  { label: 'sos', value: 'sos' },
  { label: 'spotify', value: 'spotify' },
  { label: 'star-empty', value: 'star-empty' },
  { label: 'star-filled', value: 'star-filled' },
  { label: 'star-half', value: 'star-half' },
  { label: 'sticky', value: 'sticky' },
  { label: 'store', value: 'store' },
  { label: 'superhero-alt', value: 'superhero-alt' },
  { label: 'superhero', value: 'superhero' },
  { label: 'table-col-after', value: 'table-col-after' },
  { label: 'table-col-before', value: 'table-col-before' },
  { label: 'table-col-delete', value: 'table-col-delete' },
  { label: 'table-row-after', value: 'table-row-after' },
  { label: 'table-row-before', value: 'table-row-before' },
  { label: 'table-row-delete', value: 'table-row-delete' },
  { label: 'tablet', value: 'tablet' },
  { label: 'tag', value: 'tag' },
  { label: 'tagcloud', value: 'tagcloud' },
  { label: 'testimonial', value: 'testimonial' },
  { label: 'text-page', value: 'text-page' },
  { label: 'text', value: 'text' },
  { label: 'thumbs-down', value: 'thumbs-down' },
  { label: 'thumbs-up', value: 'thumbs-up' },
  { label: 'tickets-alt', value: 'tickets-alt' },
  { label: 'tickets', value: 'tickets' },
  { label: 'tide', value: 'tide' },
  { label: 'translation', value: 'translation' },
  { label: 'trash', value: 'trash' },
  { label: 'twitch', value: 'twitch' },
  { label: 'twitter-alt', value: 'twitter-alt' },
  { label: 'twitter', value: 'twitter' },
  { label: 'undo', value: 'undo' },
  { label: 'universal-access-alt', value: 'universal-access-alt' },
  { label: 'universal-access', value: 'universal-access' },
  { label: 'unlock', value: 'unlock' },
  { label: 'update-alt', value: 'update-alt' },
  { label: 'update', value: 'update' },
  { label: 'upload', value: 'upload' },
  { label: 'vault', value: 'vault' },
  { label: 'video-alt', value: 'video-alt' },
  { label: 'video-alt2', value: 'video-alt2' },
  { label: 'video-alt3', value: 'video-alt3' },
  { label: 'visibility', value: 'visibility' },
  { label: 'warning', value: 'warning' },
  { label: 'welcome-add-page', value: 'welcome-add-page' },
  { label: 'welcome-comments', value: 'welcome-comments' },
  { label: 'welcome-learn-more', value: 'welcome-learn-more' },
  { label: 'welcome-view-site', value: 'welcome-view-site' },
  { label: 'welcome-widgets-menus', value: 'welcome-widgets-menus' },
  { label: 'welcome-write-blog', value: 'welcome-write-blog' },
  { label: 'whatsapp', value: 'whatsapp' },
  { label: 'wordpress-alt', value: 'wordpress-alt' },
  { label: 'wordpress', value: 'wordpress' },
  { label: 'xing', value: 'xing' },
  { label: 'yes-alt', value: 'yes-alt' },
  { label: 'yes', value: 'yes' },
  { label: 'youtube', value: 'youtube' }
]
