import { __ } from '../../../Utils/i18nwrap'

export const modules = [
  { name: 'create_cpt', label: __('Create CPT', 'bit-integrations'), is_pro: false },
  { name: 'update_cpt', label: __('Update CPT', 'bit-integrations'), is_pro: true },
  { name: 'delete_cpt', label: __('Delete CPT', 'bit-integrations'), is_pro: true },
  { name: 'create_taxonomy', label: __('Create Taxonomy', 'bit-integrations'), is_pro: true },
  { name: 'update_taxonomy', label: __('Update Taxonomy', 'bit-integrations'), is_pro: true },
  { name: 'delete_taxonomy', label: __('Delete Taxonomy', 'bit-integrations'), is_pro: true },
  {
    name: 'associate_taxonomy_to_cpt',
    label: __('Associate Taxonomy To CPT', 'bit-integrations'),
    is_pro: true
  },
  { name: 'create_option_page', label: __('Create Option Page', 'bit-integrations'), is_pro: true },
  { name: 'update_option_page', label: __('Update Option Page', 'bit-integrations'), is_pro: true },
  { name: 'delete_option_page', label: __('Delete Option Page', 'bit-integrations'), is_pro: true },
  { name: 'delete_meta_group', label: __('Delete Meta Field Group', 'bit-integrations'), is_pro: true },
  { name: 'delete_dynamic_block', label: __('Delete Dynamic Block', 'bit-integrations'), is_pro: true }
]

export const cptFields = [
  { label: __('Post Name', 'bit-integrations'), key: 'post_name', required: true },
  { label: __('Singular Label', 'bit-integrations'), key: 'singular_label', required: true },
  { label: __('Plural Label', 'bit-integrations'), key: 'plural_label', required: true },
  { label: __('REST API base slug', 'bit-integrations'), key: 'rest_base', required: false },
  { label: __('Menu position', 'bit-integrations'), key: 'menu_position', required: false },
  { label: __('Capability type', 'bit-integrations'), key: 'capability_type', required: false },
  { label: __('Custom rewrite rules', 'bit-integrations'), key: 'custom_rewrite', required: false },
  { label: __('Custom query var', 'bit-integrations'), key: 'custom_query_var', required: false }
]

export const cptLabels = [
  { label: __('Menu Name', 'bit-integrations'), key: 'menu_name' },
  { label: __('All Items', 'bit-integrations'), key: 'all_items' },
  { label: __('Add New', 'bit-integrations'), key: 'add_new' },
  { label: __('Add New Item', 'bit-integrations'), key: 'add_new_item' },
  { label: __('Edit Item', 'bit-integrations'), key: 'edit_item' },
  { label: __('New Item', 'bit-integrations'), key: 'new_item' },
  { label: __('View Item', 'bit-integrations'), key: 'view_item' },
  { label: __('View Items', 'bit-integrations'), key: 'view_items' },
  { label: __('Search Item', 'bit-integrations'), key: 'search_item' },
  { label: __('Not Found', 'bit-integrations'), key: 'not_found' },
  { label: __('Not Found in Trash', 'bit-integrations'), key: 'not_found_in_trash' },
  { label: __('Parent Item Colon', 'bit-integrations'), key: 'parent_item_colon' },
  { label: __('Featured Image', 'bit-integrations'), key: 'featured_image' },
  { label: __('Set Featured Image', 'bit-integrations'), key: 'set_featured_image' },
  { label: __('Remove Featured Image', 'bit-integrations'), key: 'remove_featured_image' },
  { label: __('Use Featured Image', 'bit-integrations'), key: 'use_featured_image' },
  { label: __('Archives', 'bit-integrations'), key: 'archives' },
  { label: __('Insert into Item', 'bit-integrations'), key: 'insert_into_item' },
  { label: __('Uploaded to This Item', 'bit-integrations'), key: 'uploaded_to_this_item' },
  { label: __('Filter Items List', 'bit-integrations'), key: 'filter_items_list' },
  { label: __('Items List Navigation', 'bit-integrations'), key: 'items_list_navigation' },
  { label: __('Items List', 'bit-integrations'), key: 'items_list' },
  { label: __('Filter by Date', 'bit-integrations'), key: 'filter_by_date' },
  { label: __('Item Published', 'bit-integrations'), key: 'item_published' },
  { label: __('Item Published Privately', 'bit-integrations'), key: 'item_published_privately' },
  { label: __('Item Reverted to Draft', 'bit-integrations'), key: 'item_reverted_to_draft' },
  { label: __('Item Scheduled', 'bit-integrations'), key: 'item_scheduled' },
  { label: __('Item Updated', 'bit-integrations'), key: 'item_updated' }
]

export const taxonomyLabels = [
  { label: __('Menu Name', 'bit-integrations'), key: 'name' },
  { label: __('Singular name', 'bit-integrations'), key: 'singular_name' },
  { label: __('Search Items', 'bit-integrations'), key: 'search_items' },
  { label: __('Popular Items', 'bit-integrations'), key: 'popular_items' },
  { label: __('All Items', 'bit-integrations'), key: 'all_items' },
  { label: __('Parent Item', 'bit-integrations'), key: 'parent_item' },
  { label: __('Parent Item Colon', 'bit-integrations'), key: 'parent_item_colon' },
  { label: __('Edit Item', 'bit-integrations'), key: 'edit_item' },
  { label: __('View Item', 'bit-integrations'), key: 'view_item' },
  { label: __('Update Item', 'bit-integrations'), key: 'update_item' },
  { label: __('Add New Item', 'bit-integrations'), key: 'add_new_item' },
  { label: __('New Item Name', 'bit-integrations'), key: 'new_item_name' },
  {
    label: __('Separate Items With Commas', 'bit-integrations'),
    key: 'separate_items_with_commas'
  },
  { label: __('Add or Remove Items', 'bit-integrations'), key: 'add_or_remove_items' },
  {
    label: __('Choose From Most Used', 'bit-integrations'),
    key: 'choose_from_most_used'
  },
  { label: __('Not Found', 'bit-integrations'), key: 'not_found' },
  { label: __('No Terms', 'bit-integrations'), key: 'no_terms' },
  { label: __('Filter By Item', 'bit-integrations'), key: 'filter_by_item' },
  {
    label: __('Items List Navigation', 'bit-integrations'),
    key: 'items_list_navigation'
  },
  { label: __('Items List', 'bit-integrations'), key: 'items_list' },
  { label: __('Most Used', 'bit-integrations'), key: 'most_used' },
  { label: __('Back To Items', 'bit-integrations'), key: 'back_to_items' }
]

export const taxonomyFields = [
  { label: __('Slug', 'bit-integrations'), key: 'slug', required: true },
  { label: __('Singular Label', 'bit-integrations'), key: 'singular_label', required: true },
  { label: __('Plural Label', 'bit-integrations'), key: 'plural_label', required: true },
  { label: __('REST API base slug', 'bit-integrations'), key: 'rest_base', required: false },
  {
    label: __('REST API Controller Class', 'bit-integrations'),
    key: 'rest_controller_class',
    required: false
  },
  { label: __('Menu position', 'bit-integrations'), key: 'menu_position', required: false },
  { label: __('Capability type', 'bit-integrations'), key: 'capability_type', required: false },
  { label: __('Custom rewrite rules', 'bit-integrations'), key: 'custom_rewrite', required: false },
  { label: __('Custom query var', 'bit-integrations'), key: 'custom_query_var', required: false },
  { label: __('Default Term', 'bit-integrations'), key: 'default_term', required: false }
]

export const optionPageFields = [
  { label: __('Page Title', 'bit-integrations'), key: 'pageTitle', required: true },
  { label: __('Menu Title', 'bit-integrations'), key: 'menuTitle', required: true },
  { label: __('Menu Slug', 'bit-integrations'), key: 'menuSlug', required: true },
  { label: __('Menu Position', 'bit-integrations'), key: 'position', required: true },
  { label: __('Page Description', 'bit-integrations'), key: 'description', required: false }
]

export const supports = [
  { label: __('Title'), value: 'title' },
  { label: __('Editor'), value: 'editor' },
  { label: __('Comments'), value: 'comments' },
  { label: __('Revisions'), value: 'revisions' },
  { label: __('Trackbacks'), value: 'trackbacks' },
  { label: __('Author'), value: 'author' },
  { label: __('Excerpt'), value: 'excerpt' },
  { label: __('Page Attributes'), value: 'page-attributes' },
  { label: __('Thumbnail'), value: 'thumbnail' },
  { label: __('Custom Fields'), value: 'custom-fields' },
  { label: __('Post Formats'), value: 'post-formats' }
]

export const capabilities = [
  { label: __('Manage Terms'), value: 'manage_terms' },
  { label: __('Edit Terms'), value: 'edit_terms' },
  { label: __('Delete Terms'), value: 'delete_terms' },
  { label: __('Assign Terms'), value: 'assign_terms' }
]

export const cptIcons = [
  { label: __('Admin Appearance', 'bit-integrations'), value: 'admin-appearance' },
  { label: __('Admin Collapse', 'bit-integrations'), value: 'admin-collapse' },
  { label: __('Admin Comments', 'bit-integrations'), value: 'admin-comments' },
  { label: __('Admin Customizer', 'bit-integrations'), value: 'admin-customizer' },
  { label: __('Admin Generic', 'bit-integrations'), value: 'admin-generic' },
  { label: __('Admin Home', 'bit-integrations'), value: 'admin-home' },
  { label: __('Admin Links', 'bit-integrations'), value: 'admin-links' },
  { label: __('Admin Media', 'bit-integrations'), value: 'admin-media' },
  { label: __('Admin Multisite', 'bit-integrations'), value: 'admin-multisite' },
  { label: __('Admin Network', 'bit-integrations'), value: 'admin-network' },
  { label: __('Admin Page', 'bit-integrations'), value: 'admin-page' },
  { label: __('Admin Plugins', 'bit-integrations'), value: 'admin-plugins' },
  { label: __('Admin Post', 'bit-integrations'), value: 'admin-post' },
  { label: __('Admin Settings', 'bit-integrations'), value: 'admin-settings' },
  { label: __('Admin Site Alt', 'bit-integrations'), value: 'admin-site-alt' },
  { label: __('Admin Site Alt2', 'bit-integrations'), value: 'admin-site-alt2' },
  { label: __('Admin Site Alt3', 'bit-integrations'), value: 'admin-site-alt3' },
  { label: __('Admin Site', 'bit-integrations'), value: 'admin-site' },
  { label: __('Admin Tools', 'bit-integrations'), value: 'admin-tools' },
  { label: __('Admin Users', 'bit-integrations'), value: 'admin-users' },
  { label: __('Airplane', 'bit-integrations'), value: 'airplane' },
  { label: __('Album', 'bit-integrations'), value: 'album' },
  { label: __('Align Center', 'bit-integrations'), value: 'align-center' },
  { label: __('Align Full Width', 'bit-integrations'), value: 'align-full-width' },
  { label: __('Align Left', 'bit-integrations'), value: 'align-left' },
  { label: __('Align None', 'bit-integrations'), value: 'align-none' },
  { label: __('Align Pull Left', 'bit-integrations'), value: 'align-pull-left' },
  { label: __('Align Pull Right', 'bit-integrations'), value: 'align-pull-right' },
  { label: __('Align Right', 'bit-integrations'), value: 'align-right' },
  { label: __('Align Wide', 'bit-integrations'), value: 'align-wide' },
  { label: __('Amazon', 'bit-integrations'), value: 'amazon' },
  { label: __('Analytics', 'bit-integrations'), value: 'analytics' },
  { label: __('Archive', 'bit-integrations'), value: 'archive' },
  { label: __('Arrow Down Alt', 'bit-integrations'), value: 'arrow-down-alt' },
  { label: __('Arrow Down Alt2', 'bit-integrations'), value: 'arrow-down-alt2' },
  { label: __('Arrow Down', 'bit-integrations'), value: 'arrow-down' },
  { label: __('Arrow Left Alt', 'bit-integrations'), value: 'arrow-left-alt' },
  { label: __('Arrow Left Alt2', 'bit-integrations'), value: 'arrow-left-alt2' },
  { label: __('Arrow Left', 'bit-integrations'), value: 'arrow-left' },
  { label: __('Arrow Right Alt', 'bit-integrations'), value: 'arrow-right-alt' },
  { label: __('Arrow Right Alt2', 'bit-integrations'), value: 'arrow-right-alt2' },
  { label: __('Arrow Right', 'bit-integrations'), value: 'arrow-right' },
  { label: __('Arrow Up Alt', 'bit-integrations'), value: 'arrow-up-alt' },
  { label: __('Arrow Up Alt2', 'bit-integrations'), value: 'arrow-up-alt2' },
  { label: __('Arrow Up Duplicate', 'bit-integrations'), value: 'arrow-up-duplicate' },
  { label: __('Arrow Up', 'bit-integrations'), value: 'arrow-up' },
  { label: __('Art', 'bit-integrations'), value: 'art' },
  { label: __('Awards', 'bit-integrations'), value: 'awards' },
  { label: __('Backup', 'bit-integrations'), value: 'backup' },
  { label: __('Bank', 'bit-integrations'), value: 'bank' },
  { label: __('Beer', 'bit-integrations'), value: 'beer' },
  { label: __('Bell', 'bit-integrations'), value: 'bell' },
  { label: __('Block Default', 'bit-integrations'), value: 'block-default' },
  { label: __('Book Alt', 'bit-integrations'), value: 'book-alt' },
  { label: __('Book', 'bit-integrations'), value: 'book' },
  { label: __('Buddicons Activity', 'bit-integrations'), value: 'buddicons-activity' },
  { label: __('Buddicons Bbpress Logo', 'bit-integrations'), value: 'buddicons-bbpress-logo' },
  { label: __('Buddicons Buddypress Logo', 'bit-integrations'), value: 'buddicons-buddypress-logo' },
  { label: __('Buddicons Community', 'bit-integrations'), value: 'buddicons-community' },
  { label: __('Buddicons Forums', 'bit-integrations'), value: 'buddicons-forums' },
  { label: __('Buddicons Friends', 'bit-integrations'), value: 'buddicons-friends' },
  { label: __('Buddicons Groups', 'bit-integrations'), value: 'buddicons-groups' },
  { label: __('Buddicons Pm', 'bit-integrations'), value: 'buddicons-pm' },
  { label: __('Buddicons Replies', 'bit-integrations'), value: 'buddicons-replies' },
  { label: __('Buddicons Topics', 'bit-integrations'), value: 'buddicons-topics' },
  { label: __('Buddicons Tracking', 'bit-integrations'), value: 'buddicons-tracking' },
  { label: __('Building', 'bit-integrations'), value: 'building' },
  { label: __('Businessman', 'bit-integrations'), value: 'businessman' },
  { label: __('Businessperson', 'bit-integrations'), value: 'businessperson' },
  { label: __('Businesswoman', 'bit-integrations'), value: 'businesswoman' },
  { label: __('Button', 'bit-integrations'), value: 'button' },
  { label: __('Calculator', 'bit-integrations'), value: 'calculator' },
  { label: __('Calendar Alt', 'bit-integrations'), value: 'calendar-alt' },
  { label: __('Calendar', 'bit-integrations'), value: 'calendar' },
  { label: __('Camera Alt', 'bit-integrations'), value: 'camera-alt' },
  { label: __('Camera', 'bit-integrations'), value: 'camera' },
  { label: __('Car', 'bit-integrations'), value: 'car' },
  { label: __('Carrot', 'bit-integrations'), value: 'carrot' },
  { label: __('Cart', 'bit-integrations'), value: 'cart' },
  { label: __('Category', 'bit-integrations'), value: 'category' },
  { label: __('Chart Area', 'bit-integrations'), value: 'chart-area' },
  { label: __('Chart Bar', 'bit-integrations'), value: 'chart-bar' },
  { label: __('Chart Line', 'bit-integrations'), value: 'chart-line' },
  { label: __('Chart Pie', 'bit-integrations'), value: 'chart-pie' },
  { label: __('Clipboard', 'bit-integrations'), value: 'clipboard' },
  { label: __('Clock', 'bit-integrations'), value: 'clock' },
  { label: __('Cloud Saved', 'bit-integrations'), value: 'cloud-saved' },
  { label: __('Cloud Upload', 'bit-integrations'), value: 'cloud-upload' },
  { label: __('Cloud', 'bit-integrations'), value: 'cloud' },
  { label: __('Code Standards', 'bit-integrations'), value: 'code-standards' },
  { label: __('Coffee', 'bit-integrations'), value: 'coffee' },
  { label: __('Color Picker', 'bit-integrations'), value: 'color-picker' },
  { label: __('Columns', 'bit-integrations'), value: 'columns' },
  { label: __('Controls Back', 'bit-integrations'), value: 'controls-back' },
  { label: __('Controls Forward', 'bit-integrations'), value: 'controls-forward' },
  { label: __('Controls Pause', 'bit-integrations'), value: 'controls-pause' },
  { label: __('Controls Play', 'bit-integrations'), value: 'controls-play' },
  { label: __('Controls Repeat', 'bit-integrations'), value: 'controls-repeat' },
  { label: __('Controls Skipback', 'bit-integrations'), value: 'controls-skipback' },
  { label: __('Controls Skipforward', 'bit-integrations'), value: 'controls-skipforward' },
  { label: __('Controls Volumeoff', 'bit-integrations'), value: 'controls-volumeoff' },
  { label: __('Controls Volumeon', 'bit-integrations'), value: 'controls-volumeon' },
  { label: __('Cover Image', 'bit-integrations'), value: 'cover-image' },
  { label: __('Dashboard', 'bit-integrations'), value: 'dashboard' },
  { label: __('Database Add', 'bit-integrations'), value: 'database-add' },
  { label: __('Database Export', 'bit-integrations'), value: 'database-export' },
  { label: __('Database Import', 'bit-integrations'), value: 'database-import' },
  { label: __('Database Remove', 'bit-integrations'), value: 'database-remove' },
  { label: __('Database View', 'bit-integrations'), value: 'database-view' },
  { label: __('Database', 'bit-integrations'), value: 'database' },
  { label: __('Desktop', 'bit-integrations'), value: 'desktop' },
  { label: __('Dismiss', 'bit-integrations'), value: 'dismiss' },
  { label: __('Download', 'bit-integrations'), value: 'download' },
  { label: __('Drumstick', 'bit-integrations'), value: 'drumstick' },
  { label: __('Edit Large', 'bit-integrations'), value: 'edit-large' },
  { label: __('Edit Page', 'bit-integrations'), value: 'edit-page' },
  { label: __('Edit', 'bit-integrations'), value: 'edit' },
  { label: __('Editor Aligncenter', 'bit-integrations'), value: 'editor-aligncenter' },
  { label: __('Editor Alignleft', 'bit-integrations'), value: 'editor-alignleft' },
  { label: __('Editor Alignright', 'bit-integrations'), value: 'editor-alignright' },
  { label: __('Editor Bold', 'bit-integrations'), value: 'editor-bold' },
  { label: __('Editor Break', 'bit-integrations'), value: 'editor-break' },
  { label: __('Editor Code Duplicate', 'bit-integrations'), value: 'editor-code-duplicate' },
  { label: __('Editor Code', 'bit-integrations'), value: 'editor-code' },
  { label: __('Editor Contract', 'bit-integrations'), value: 'editor-contract' },
  { label: __('Editor Customchar', 'bit-integrations'), value: 'editor-customchar' },
  { label: __('Editor Expand', 'bit-integrations'), value: 'editor-expand' },
  { label: __('Editor Help', 'bit-integrations'), value: 'editor-help' },
  { label: __('Editor Indent', 'bit-integrations'), value: 'editor-indent' },
  { label: __('Editor Insertmore', 'bit-integrations'), value: 'editor-insertmore' },
  { label: __('Editor Italic', 'bit-integrations'), value: 'editor-italic' },
  { label: __('Editor Justify', 'bit-integrations'), value: 'editor-justify' },
  { label: __('Editor Kitchensink', 'bit-integrations'), value: 'editor-kitchensink' },
  { label: __('Editor Ltr', 'bit-integrations'), value: 'editor-ltr' },
  { label: __('Editor Ol Rtl', 'bit-integrations'), value: 'editor-ol-rtl' },
  { label: __('Editor Ol', 'bit-integrations'), value: 'editor-ol' },
  { label: __('Editor Outdent', 'bit-integrations'), value: 'editor-outdent' },
  { label: __('Editor Paragraph', 'bit-integrations'), value: 'editor-paragraph' },
  { label: __('Editor Paste Text', 'bit-integrations'), value: 'editor-paste-text' },
  { label: __('Editor Paste Word', 'bit-integrations'), value: 'editor-paste-word' },
  { label: __('Editor Quote', 'bit-integrations'), value: 'editor-quote' },
  { label: __('Editor Removeformatting', 'bit-integrations'), value: 'editor-removeformatting' },
  { label: __('Editor Rtl', 'bit-integrations'), value: 'editor-rtl' },
  { label: __('Editor Spellcheck', 'bit-integrations'), value: 'editor-spellcheck' },
  { label: __('Editor Strikethrough', 'bit-integrations'), value: 'editor-strikethrough' },
  { label: __('Editor Table', 'bit-integrations'), value: 'editor-table' },
  { label: __('Editor Textcolor', 'bit-integrations'), value: 'editor-textcolor' },
  { label: __('Editor Ul', 'bit-integrations'), value: 'editor-ul' },
  { label: __('Editor Underline', 'bit-integrations'), value: 'editor-underline' },
  { label: __('Editor Unlink', 'bit-integrations'), value: 'editor-unlink' },
  { label: __('Editor Video', 'bit-integrations'), value: 'editor-video' },
  { label: __('Ellipsis', 'bit-integrations'), value: 'ellipsis' },
  { label: __('Email Alt', 'bit-integrations'), value: 'email-alt' },
  { label: __('Email Alt2', 'bit-integrations'), value: 'email-alt2' },
  { label: __('Email', 'bit-integrations'), value: 'email' },
  { label: __('Embed Audio', 'bit-integrations'), value: 'embed-audio' },
  { label: __('Embed Generic', 'bit-integrations'), value: 'embed-generic' },
  { label: __('Embed Photo', 'bit-integrations'), value: 'embed-photo' },
  { label: __('Embed Post', 'bit-integrations'), value: 'embed-post' },
  { label: __('Embed Video', 'bit-integrations'), value: 'embed-video' },
  { label: __('Excerpt View', 'bit-integrations'), value: 'excerpt-view' },
  { label: __('Exit', 'bit-integrations'), value: 'exit' },
  { label: __('External', 'bit-integrations'), value: 'external' },
  { label: __('Facebook Alt', 'bit-integrations'), value: 'facebook-alt' },
  { label: __('Facebook', 'bit-integrations'), value: 'facebook' },
  { label: __('Feedback', 'bit-integrations'), value: 'feedback' },
  { label: __('Filter', 'bit-integrations'), value: 'filter' },
  { label: __('Flag', 'bit-integrations'), value: 'flag' },
  { label: __('Food', 'bit-integrations'), value: 'food' },
  { label: __('Format Aside', 'bit-integrations'), value: 'format-aside' },
  { label: __('Format Audio', 'bit-integrations'), value: 'format-audio' },
  { label: __('Format Chat', 'bit-integrations'), value: 'format-chat' },
  { label: __('Format Gallery', 'bit-integrations'), value: 'format-gallery' },
  { label: __('Format Image', 'bit-integrations'), value: 'format-image' },
  { label: __('Format Quote', 'bit-integrations'), value: 'format-quote' },
  { label: __('Format Status', 'bit-integrations'), value: 'format-status' },
  { label: __('Format Video', 'bit-integrations'), value: 'format-video' },
  { label: __('Forms', 'bit-integrations'), value: 'forms' },
  { label: __('Fullscreen Alt', 'bit-integrations'), value: 'fullscreen-alt' },
  { label: __('Fullscreen Exit Alt', 'bit-integrations'), value: 'fullscreen-exit-alt' },
  { label: __('Games', 'bit-integrations'), value: 'games' },
  { label: __('Google', 'bit-integrations'), value: 'google' },
  { label: __('Googleplus', 'bit-integrations'), value: 'googleplus' },
  { label: __('Grid View', 'bit-integrations'), value: 'grid-view' },
  { label: __('Groups', 'bit-integrations'), value: 'groups' },
  { label: __('Hammer', 'bit-integrations'), value: 'hammer' },
  { label: __('Heading', 'bit-integrations'), value: 'heading' },
  { label: __('Heart', 'bit-integrations'), value: 'heart' },
  { label: __('Hidden', 'bit-integrations'), value: 'hidden' },
  { label: __('Hourglass', 'bit-integrations'), value: 'hourglass' },
  { label: __('Html', 'bit-integrations'), value: 'html' },
  { label: __('Id Alt', 'bit-integrations'), value: 'id-alt' },
  { label: __('Id', 'bit-integrations'), value: 'id' },
  { label: __('Image Crop', 'bit-integrations'), value: 'image-crop' },
  { label: __('Image Filter', 'bit-integrations'), value: 'image-filter' },
  { label: __('Image Flip Horizontal', 'bit-integrations'), value: 'image-flip-horizontal' },
  { label: __('Image Flip Vertical', 'bit-integrations'), value: 'image-flip-vertical' },
  { label: __('Image Rotate Left', 'bit-integrations'), value: 'image-rotate-left' },
  { label: __('Image Rotate Right', 'bit-integrations'), value: 'image-rotate-right' },
  { label: __('Image Rotate', 'bit-integrations'), value: 'image-rotate' },
  { label: __('Images Alt', 'bit-integrations'), value: 'images-alt' },
  { label: __('Images Alt2', 'bit-integrations'), value: 'images-alt2' },
  { label: __('Index Card', 'bit-integrations'), value: 'index-card' },
  { label: __('Info Outline', 'bit-integrations'), value: 'info-outline' },
  { label: __('Info', 'bit-integrations'), value: 'info' },
  { label: __('Insert After', 'bit-integrations'), value: 'insert-after' },
  { label: __('Insert Before', 'bit-integrations'), value: 'insert-before' },
  { label: __('Insert', 'bit-integrations'), value: 'insert' },
  { label: __('Instagram', 'bit-integrations'), value: 'instagram' },
  { label: __('Laptop', 'bit-integrations'), value: 'laptop' },
  { label: __('Layout', 'bit-integrations'), value: 'layout' },
  { label: __('Leftright', 'bit-integrations'), value: 'leftright' },
  { label: __('Lightbulb', 'bit-integrations'), value: 'lightbulb' },
  { label: __('Linkedin', 'bit-integrations'), value: 'linkedin' },
  { label: __('List View', 'bit-integrations'), value: 'list-view' },
  { label: __('Location Alt', 'bit-integrations'), value: 'location-alt' },
  { label: __('Location', 'bit-integrations'), value: 'location' },
  { label: __('Lock Duplicate', 'bit-integrations'), value: 'lock-duplicate' },
  { label: __('Lock', 'bit-integrations'), value: 'lock' },
  { label: __('Marker', 'bit-integrations'), value: 'marker' },
  { label: __('Media Archive', 'bit-integrations'), value: 'media-archive' },
  { label: __('Media Audio', 'bit-integrations'), value: 'media-audio' },
  { label: __('Media Code', 'bit-integrations'), value: 'media-code' },
  { label: __('Media Default', 'bit-integrations'), value: 'media-default' },
  { label: __('Media Document', 'bit-integrations'), value: 'media-document' },
  { label: __('Media Interactive', 'bit-integrations'), value: 'media-interactive' },
  { label: __('Media Spreadsheet', 'bit-integrations'), value: 'media-spreadsheet' },
  { label: __('Media Text', 'bit-integrations'), value: 'media-text' },
  { label: __('Media Video', 'bit-integrations'), value: 'media-video' },
  { label: __('Megaphone', 'bit-integrations'), value: 'megaphone' },
  { label: __('Menu Alt', 'bit-integrations'), value: 'menu-alt' },
  { label: __('Menu Alt2', 'bit-integrations'), value: 'menu-alt2' },
  { label: __('Menu Alt3', 'bit-integrations'), value: 'menu-alt3' },
  { label: __('Menu', 'bit-integrations'), value: 'menu' },
  { label: __('Microphone', 'bit-integrations'), value: 'microphone' },
  { label: __('Migrate', 'bit-integrations'), value: 'migrate' },
  { label: __('Minus', 'bit-integrations'), value: 'minus' },
  { label: __('Money Alt', 'bit-integrations'), value: 'money-alt' },
  { label: __('Money', 'bit-integrations'), value: 'money' },
  { label: __('Move', 'bit-integrations'), value: 'move' },
  { label: __('Nametag', 'bit-integrations'), value: 'nametag' },
  { label: __('Networking', 'bit-integrations'), value: 'networking' },
  { label: __('No Alt', 'bit-integrations'), value: 'no-alt' },
  { label: __('No', 'bit-integrations'), value: 'no' },
  { label: __('Open Folder', 'bit-integrations'), value: 'open-folder' },
  { label: __('Palmtree', 'bit-integrations'), value: 'palmtree' },
  { label: __('Paperclip', 'bit-integrations'), value: 'paperclip' },
  { label: __('Pdf', 'bit-integrations'), value: 'pdf' },
  { label: __('Performance', 'bit-integrations'), value: 'performance' },
  { label: __('Pets', 'bit-integrations'), value: 'pets' },
  { label: __('Phone', 'bit-integrations'), value: 'phone' },
  { label: __('Pinterest', 'bit-integrations'), value: 'pinterest' },
  { label: __('Playlist Audio', 'bit-integrations'), value: 'playlist-audio' },
  { label: __('Playlist Video', 'bit-integrations'), value: 'playlist-video' },
  { label: __('Plugins Checked', 'bit-integrations'), value: 'plugins-checked' },
  { label: __('Plus Alt', 'bit-integrations'), value: 'plus-alt' },
  { label: __('Plus Alt2', 'bit-integrations'), value: 'plus-alt2' },
  { label: __('Plus', 'bit-integrations'), value: 'plus' },
  { label: __('Podio', 'bit-integrations'), value: 'podio' },
  { label: __('Portfolio', 'bit-integrations'), value: 'portfolio' },
  { label: __('Post Status', 'bit-integrations'), value: 'post-status' },
  { label: __('Pressthis', 'bit-integrations'), value: 'pressthis' },
  { label: __('Printer', 'bit-integrations'), value: 'printer' },
  { label: __('Privacy', 'bit-integrations'), value: 'privacy' },
  { label: __('Products', 'bit-integrations'), value: 'products' },
  { label: __('Randomize', 'bit-integrations'), value: 'randomize' },
  { label: __('Reddit', 'bit-integrations'), value: 'reddit' },
  { label: __('Redo', 'bit-integrations'), value: 'redo' },
  { label: __('Remove', 'bit-integrations'), value: 'remove' },
  { label: __('Rest Api', 'bit-integrations'), value: 'rest-api' },
  { label: __('Rss', 'bit-integrations'), value: 'rss' },
  { label: __('Saved', 'bit-integrations'), value: 'saved' },
  { label: __('Schedule', 'bit-integrations'), value: 'schedule' },
  { label: __('Screenoptions', 'bit-integrations'), value: 'screenoptions' },
  { label: __('Search', 'bit-integrations'), value: 'search' },
  { label: __('Share Alt', 'bit-integrations'), value: 'share-alt' },
  { label: __('Share Alt2', 'bit-integrations'), value: 'share-alt2' },
  { label: __('Share', 'bit-integrations'), value: 'share' },
  { label: __('Shield Alt', 'bit-integrations'), value: 'shield-alt' },
  { label: __('Shield', 'bit-integrations'), value: 'shield' },
  { label: __('Shortcode', 'bit-integrations'), value: 'shortcode' },
  { label: __('Slides', 'bit-integrations'), value: 'slides' },
  { label: __('Smartphone', 'bit-integrations'), value: 'smartphone' },
  { label: __('Smiley', 'bit-integrations'), value: 'smiley' },
  { label: __('Sort', 'bit-integrations'), value: 'sort' },
  { label: __('Sos', 'bit-integrations'), value: 'sos' },
  { label: __('Spotify', 'bit-integrations'), value: 'spotify' },
  { label: __('Star Empty', 'bit-integrations'), value: 'star-empty' },
  { label: __('Star Filled', 'bit-integrations'), value: 'star-filled' },
  { label: __('Star Half', 'bit-integrations'), value: 'star-half' },
  { label: __('Sticky', 'bit-integrations'), value: 'sticky' },
  { label: __('Store', 'bit-integrations'), value: 'store' },
  { label: __('Superhero Alt', 'bit-integrations'), value: 'superhero-alt' },
  { label: __('Superhero', 'bit-integrations'), value: 'superhero' },
  { label: __('Table Col After', 'bit-integrations'), value: 'table-col-after' },
  { label: __('Table Col Before', 'bit-integrations'), value: 'table-col-before' },
  { label: __('Table Col Delete', 'bit-integrations'), value: 'table-col-delete' },
  { label: __('Table Row After', 'bit-integrations'), value: 'table-row-after' },
  { label: __('Table Row Before', 'bit-integrations'), value: 'table-row-before' },
  { label: __('Table Row Delete', 'bit-integrations'), value: 'table-row-delete' },
  { label: __('Tablet', 'bit-integrations'), value: 'tablet' },
  { label: __('Tag', 'bit-integrations'), value: 'tag' },
  { label: __('Tagcloud', 'bit-integrations'), value: 'tagcloud' },
  { label: __('Testimonial', 'bit-integrations'), value: 'testimonial' },
  { label: __('Text Page', 'bit-integrations'), value: 'text-page' },
  { label: __('Text', 'bit-integrations'), value: 'text' },
  { label: __('Thumbs Down', 'bit-integrations'), value: 'thumbs-down' },
  { label: __('Thumbs Up', 'bit-integrations'), value: 'thumbs-up' },
  { label: __('Tickets Alt', 'bit-integrations'), value: 'tickets-alt' },
  { label: __('Tickets', 'bit-integrations'), value: 'tickets' },
  { label: __('Tide', 'bit-integrations'), value: 'tide' },
  { label: __('Translation', 'bit-integrations'), value: 'translation' },
  { label: __('Trash', 'bit-integrations'), value: 'trash' },
  { label: __('Twitch', 'bit-integrations'), value: 'twitch' },
  { label: __('Twitter Alt', 'bit-integrations'), value: 'twitter-alt' },
  { label: __('Twitter', 'bit-integrations'), value: 'twitter' },
  { label: __('Undo', 'bit-integrations'), value: 'undo' },
  { label: __('Universal Access Alt', 'bit-integrations'), value: 'universal-access-alt' },
  { label: __('Universal Access', 'bit-integrations'), value: 'universal-access' },
  { label: __('Unlock', 'bit-integrations'), value: 'unlock' },
  { label: __('Update Alt', 'bit-integrations'), value: 'update-alt' },
  { label: __('Update', 'bit-integrations'), value: 'update' },
  { label: __('Upload', 'bit-integrations'), value: 'upload' },
  { label: __('Vault', 'bit-integrations'), value: 'vault' },
  { label: __('Video Alt', 'bit-integrations'), value: 'video-alt' },
  { label: __('Video Alt2', 'bit-integrations'), value: 'video-alt2' },
  { label: __('Video Alt3', 'bit-integrations'), value: 'video-alt3' },
  { label: __('Visibility', 'bit-integrations'), value: 'visibility' },
  { label: __('Warning', 'bit-integrations'), value: 'warning' },
  { label: __('Welcome Add Page', 'bit-integrations'), value: 'welcome-add-page' },
  { label: __('Welcome Comments', 'bit-integrations'), value: 'welcome-comments' },
  { label: __('Welcome Learn More', 'bit-integrations'), value: 'welcome-learn-more' },
  { label: __('Welcome View Site', 'bit-integrations'), value: 'welcome-view-site' },
  { label: __('Welcome Widgets Menus', 'bit-integrations'), value: 'welcome-widgets-menus' },
  { label: __('Welcome Write Blog', 'bit-integrations'), value: 'welcome-write-blog' },
  { label: __('Whatsapp', 'bit-integrations'), value: 'whatsapp' },
  { label: __('Wordpress Alt', 'bit-integrations'), value: 'wordpress-alt' },
  { label: __('Wordpress', 'bit-integrations'), value: 'wordpress' },
  { label: __('Xing', 'bit-integrations'), value: 'xing' },
  { label: __('Yes Alt', 'bit-integrations'), value: 'yes-alt' },
  { label: __('Yes', 'bit-integrations'), value: 'yes' },
  { label: __('Youtube', 'bit-integrations'), value: 'youtube' }
]

export const optionPageCapabilities = [
  { label: __('Moderate Comments', 'bit-integrations'), value: 'moderate_comments' },
  { label: __('Manage Options', 'bit-integrations'), value: 'manage_options' },
  { label: __('Manage Categories', 'bit-integrations'), value: 'manage_categories' },
  { label: __('Manage Links', 'bit-integrations'), value: 'manage_links' },
  { label: __('Unfiltered HTML', 'bit-integrations'), value: 'unfiltered_html' },
  { label: __("Edit Others' Posts", 'bit-integrations'), value: 'edit_others_posts' },
  { label: __('Edit Pages', 'bit-integrations'), value: 'edit_pages' },
  { label: __("Edit Others' Pages", 'bit-integrations'), value: 'edit_others_pages' },
  { label: __('Edit Published Pages', 'bit-integrations'), value: 'edit_published_pages' },
  { label: __('Publish Pages', 'bit-integrations'), value: 'publish_pages' },
  { label: __('Delete Pages', 'bit-integrations'), value: 'delete_pages' },
  { label: __("Delete Others' Pages", 'bit-integrations'), value: 'delete_others_pages' },
  { label: __('Delete Published Pages', 'bit-integrations'), value: 'delete_published_pages' },
  { label: __("Delete Others' Posts", 'bit-integrations'), value: 'delete_others_posts' },
  { label: __('Delete Private Posts', 'bit-integrations'), value: 'delete_private_posts' },
  { label: __('Edit Private Posts', 'bit-integrations'), value: 'edit_private_posts' },
  { label: __('Read Private Posts', 'bit-integrations'), value: 'read_private_posts' },
  { label: __('Delete Private Pages', 'bit-integrations'), value: 'delete_private_pages' },
  { label: __('Edit Private Pages', 'bit-integrations'), value: 'edit_private_pages' },
  { label: __('Read Private Pages', 'bit-integrations'), value: 'read_private_pages' }
]
