#!/usr/bin/env /usr/bin/bash

PLUGIN_DIR="$PWD"


rm -rf "$PLUGIN_DIR/build";
mkdir -p "$PLUGIN_DIR/build/bit-integrations";
BUILD_DIR="$PLUGIN_DIR/build/bit-integrations";

if [ ! -d "$PLUGIN_DIR/languages" ]; then
    mkdir "$PLUGIN_DIR/languages";
fi

composer i -o --no-dev --ignore-platform-reqs 2>&1 >/dev/null

cd "$PLUGIN_DIR/frontend-dev" && pnpm pda

cd "$PLUGIN_DIR"

cp -r "$PLUGIN_DIR/assets"  "$BUILD_DIR/assets"
cp -r "$PLUGIN_DIR/bitwpfi.php"  "$BUILD_DIR/bitwpfi.php"
cp -r "$PLUGIN_DIR/build-hash.txt"  "$BUILD_DIR/build-hash.txt"
cp -r "$PLUGIN_DIR/composer.json"  "$BUILD_DIR/composer.json"
cp -r "$PLUGIN_DIR/includes"  "$BUILD_DIR/includes"
cp -r "$PLUGIN_DIR/languages"  "$BUILD_DIR/languages"
cp -r "$PLUGIN_DIR/readme.txt"  "$BUILD_DIR/readme.txt"
cp -r "$PLUGIN_DIR/vendor"  "$BUILD_DIR/vendor"
cp -r "$PLUGIN_DIR/views"  "$BUILD_DIR/views"