import { __ } from '../../../Utils/i18nwrap'

export const actions = [
  { label: __('Create Invoice', 'bit-integrations'), value: 'createInvoice', is_pro: true },
  { label: __('Update Invoice', 'bit-integrations'), value: 'updateInvoice', is_pro: true },
  { label: __('Delete Invoice', 'bit-integrations'), value: 'deleteInvoice', is_pro: true },
  { label: __('Create Client', 'bit-integrations'), value: 'createClient', is_pro: true },
  { label: __('Update Client', 'bit-integrations'), value: 'updateClient', is_pro: true },
  { label: __('Delete Client', 'bit-integrations'), value: 'deleteClient', is_pro: true },
  { label: __('Create Expense', 'bit-integrations'), value: 'createExpense', is_pro: true },
  { label: __('Update Expense', 'bit-integrations'), value: 'updateExpense', is_pro: true },
  { label: __('Delete Expense', 'bit-integrations'), value: 'deleteExpense', is_pro: true },
  { label: __('Create Payment', 'bit-integrations'), value: 'createPayment', is_pro: true },
  { label: __('Update Payment', 'bit-integrations'), value: 'updatePayment', is_pro: true },
  { label: __('Delete Payment', 'bit-integrations'), value: 'deletePayment', is_pro: true },
  { label: __('Create Estimate', 'bit-integrations'), value: 'createEstimate', is_pro: true },
  { label: __('Update Estimate', 'bit-integrations'), value: 'updateEstimate', is_pro: true },
  { label: __('Delete Estimate', 'bit-integrations'), value: 'deleteEstimate', is_pro: true },
  { label: __('Create Item', 'bit-integrations'), value: 'createItem', is_pro: true },
  { label: __('Update Item', 'bit-integrations'), value: 'updateItem', is_pro: true },
  { label: __('Delete Item', 'bit-integrations'), value: 'deleteItem', is_pro: true },
  { label: __('Create Tax', 'bit-integrations'), value: 'createTax', is_pro: true },
  { label: __('Update Tax', 'bit-integrations'), value: 'updateTax', is_pro: true },
  { label: __('Delete Tax', 'bit-integrations'), value: 'deleteTax', is_pro: true },
  { label: __('Create Credit Note', 'bit-integrations'), value: 'createCreditNote', is_pro: true },
  { label: __('Update Credit Note', 'bit-integrations'), value: 'updateCreditNote', is_pro: true },
  { label: __('Delete Credit Note', 'bit-integrations'), value: 'deleteCreditNote', is_pro: true },
  { label: __('Create Bill', 'bit-integrations'), value: 'createBill', is_pro: true },
  { label: __('Update Bill', 'bit-integrations'), value: 'updateBill', is_pro: true },
  { label: __('Delete Bill', 'bit-integrations'), value: 'deleteBill', is_pro: true },
  { label: __('Create Project', 'bit-integrations'), value: 'createProject', is_pro: true },
  { label: __('Update Project', 'bit-integrations'), value: 'updateProject', is_pro: true },
  { label: __('Delete Project', 'bit-integrations'), value: 'deleteProject', is_pro: true },
  { label: __('Create Time Entry', 'bit-integrations'), value: 'createTimeEntry', is_pro: true },
  { label: __('Update Time Entry', 'bit-integrations'), value: 'updateTimeEntry', is_pro: true },
  { label: __('Delete Time Entry', 'bit-integrations'), value: 'deleteTimeEntry', is_pro: true },
  { label: __('Create Service', 'bit-integrations'), value: 'createService', is_pro: true },
  { label: __('Create Recurring Profile', 'bit-integrations'), value: 'createRecurring', is_pro: true },
  { label: __('Update Recurring Profile', 'bit-integrations'), value: 'updateRecurring', is_pro: true },
  { label: __('Delete Recurring Profile', 'bit-integrations'), value: 'deleteRecurring', is_pro: true }
]

export const freshBooksStaticData = {
  createInvoice: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: true },
    { label: __('Invoice Number', 'bit-integrations'), key: 'invoiceNumber', required: false },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Due Offset Days', 'bit-integrations'), key: 'dueOffsetDays', required: false },
    { label: __('Discount Value', 'bit-integrations'), key: 'discountValue', required: false },
    { label: __('PO Number', 'bit-integrations'), key: 'poNumber', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false },
    { label: __('Status', 'bit-integrations'), key: 'status', required: false }
  ],
  updateInvoice: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Invoice Number', 'bit-integrations'), key: 'invoiceNumber', required: false },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Due Offset Days', 'bit-integrations'), key: 'dueOffsetDays', required: false },
    { label: __('Discount Value', 'bit-integrations'), key: 'discountValue', required: false },
    { label: __('PO Number', 'bit-integrations'), key: 'poNumber', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false },
    { label: __('Status', 'bit-integrations'), key: 'status', required: false }
  ],
  deleteInvoice: [],
  createClient: [
    { label: __('First Name', 'bit-integrations'), key: 'fname', required: false },
    { label: __('Last Name', 'bit-integrations'), key: 'lname', required: false },
    { label: __('Email', 'bit-integrations'), key: 'email', required: false },
    { label: __('Organization', 'bit-integrations'), key: 'organization', required: false },
    { label: __('Business Phone', 'bit-integrations'), key: 'busPhone', required: false },
    { label: __('Mobile Phone', 'bit-integrations'), key: 'mobPhone', required: false },
    { label: __('Home Phone', 'bit-integrations'), key: 'homePhone', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false },
    { label: __('Street', 'bit-integrations'), key: 'pStreet', required: false },
    { label: __('Street 2', 'bit-integrations'), key: 'pStreet2', required: false },
    { label: __('City', 'bit-integrations'), key: 'pCity', required: false },
    { label: __('Province', 'bit-integrations'), key: 'pProvince', required: false },
    { label: __('Postal Code', 'bit-integrations'), key: 'pCode', required: false },
    { label: __('Country', 'bit-integrations'), key: 'pCountry', required: false },
    { label: __('VAT Name', 'bit-integrations'), key: 'vatName', required: false },
    { label: __('VAT Number', 'bit-integrations'), key: 'vatNumber', required: false },
    { label: __('Note', 'bit-integrations'), key: 'note', required: false }
  ],
  updateClient: [
    { label: __('First Name', 'bit-integrations'), key: 'fname', required: false },
    { label: __('Last Name', 'bit-integrations'), key: 'lname', required: false },
    { label: __('Email', 'bit-integrations'), key: 'email', required: false },
    { label: __('Organization', 'bit-integrations'), key: 'organization', required: false },
    { label: __('Business Phone', 'bit-integrations'), key: 'busPhone', required: false },
    { label: __('Mobile Phone', 'bit-integrations'), key: 'mobPhone', required: false },
    { label: __('Home Phone', 'bit-integrations'), key: 'homePhone', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false },
    { label: __('Street', 'bit-integrations'), key: 'pStreet', required: false },
    { label: __('Street 2', 'bit-integrations'), key: 'pStreet2', required: false },
    { label: __('City', 'bit-integrations'), key: 'pCity', required: false },
    { label: __('Province', 'bit-integrations'), key: 'pProvince', required: false },
    { label: __('Postal Code', 'bit-integrations'), key: 'pCode', required: false },
    { label: __('Country', 'bit-integrations'), key: 'pCountry', required: false },
    { label: __('VAT Name', 'bit-integrations'), key: 'vatName', required: false },
    { label: __('VAT Number', 'bit-integrations'), key: 'vatNumber', required: false },
    { label: __('Note', 'bit-integrations'), key: 'note', required: false }
  ],
  deleteClient: [],
  createExpense: [
    { label: __('Amount', 'bit-integrations'), key: 'amount', required: true },
    { label: __('Category ID', 'bit-integrations'), key: 'categoryId', required: true },
    { label: __('Expense Date', 'bit-integrations'), key: 'expenseDate', required: true },
    { label: __('Vendor', 'bit-integrations'), key: 'vendor', required: false },
    { label: __('Staff ID', 'bit-integrations'), key: 'staffId', required: false },
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Project ID', 'bit-integrations'), key: 'projectId', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Markup Percent', 'bit-integrations'), key: 'markupPercent', required: false },
    { label: __('Tax Name 1', 'bit-integrations'), key: 'taxName1', required: false },
    { label: __('Tax Percent 1', 'bit-integrations'), key: 'taxPercent1', required: false },
    { label: __('Tax Name 2', 'bit-integrations'), key: 'taxName2', required: false },
    { label: __('Tax Percent 2', 'bit-integrations'), key: 'taxPercent2', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false }
  ],
  updateExpense: [
    { label: __('Amount', 'bit-integrations'), key: 'amount', required: false },
    { label: __('Category ID', 'bit-integrations'), key: 'categoryId', required: false },
    { label: __('Expense Date', 'bit-integrations'), key: 'expenseDate', required: false },
    { label: __('Vendor', 'bit-integrations'), key: 'vendor', required: false },
    { label: __('Staff ID', 'bit-integrations'), key: 'staffId', required: false },
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Project ID', 'bit-integrations'), key: 'projectId', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Markup Percent', 'bit-integrations'), key: 'markupPercent', required: false },
    { label: __('Tax Name 1', 'bit-integrations'), key: 'taxName1', required: false },
    { label: __('Tax Percent 1', 'bit-integrations'), key: 'taxPercent1', required: false },
    { label: __('Tax Name 2', 'bit-integrations'), key: 'taxName2', required: false },
    { label: __('Tax Percent 2', 'bit-integrations'), key: 'taxPercent2', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false }
  ],
  deleteExpense: [],
  createPayment: [
    { label: __('Amount', 'bit-integrations'), key: 'amount', required: true },
    { label: __('Date', 'bit-integrations'), key: 'date', required: true },
    { label: __('Invoice ID', 'bit-integrations'), key: 'invoiceId', required: true },
    { label: __('Type', 'bit-integrations'), key: 'type', required: true },
    { label: __('Note', 'bit-integrations'), key: 'note', required: false },
    { label: __('Order ID', 'bit-integrations'), key: 'orderId', required: false },
    { label: __('Amount Currency', 'bit-integrations'), key: 'amountCurrency', required: false },
    { label: __('From Credit', 'bit-integrations'), key: 'fromCredit', required: false }
  ],
  updatePayment: [
    { label: __('Amount', 'bit-integrations'), key: 'amount', required: false },
    { label: __('Date', 'bit-integrations'), key: 'date', required: false },
    { label: __('Invoice ID', 'bit-integrations'), key: 'invoiceId', required: false },
    { label: __('Type', 'bit-integrations'), key: 'type', required: false },
    { label: __('Note', 'bit-integrations'), key: 'note', required: false },
    { label: __('Order ID', 'bit-integrations'), key: 'orderId', required: false },
    { label: __('Amount Currency', 'bit-integrations'), key: 'amountCurrency', required: false },
    { label: __('From Credit', 'bit-integrations'), key: 'fromCredit', required: false }
  ],
  deletePayment: [],
  createEstimate: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: true },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: true },
    { label: __('Email', 'bit-integrations'), key: 'email', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false },
    { label: __('PO Number', 'bit-integrations'), key: 'poNumber', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false },
    { label: __('Status', 'bit-integrations'), key: 'status', required: false }
  ],
  updateEstimate: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: false },
    { label: __('Email', 'bit-integrations'), key: 'email', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false },
    { label: __('PO Number', 'bit-integrations'), key: 'poNumber', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false },
    { label: __('Status', 'bit-integrations'), key: 'status', required: false }
  ],
  deleteEstimate: [],
  createItem: [
    { label: __('Name', 'bit-integrations'), key: 'name', required: true },
    { label: __('Description', 'bit-integrations'), key: 'description', required: false },
    { label: __('SKU', 'bit-integrations'), key: 'sku', required: false },
    { label: __('Quantity', 'bit-integrations'), key: 'qty', required: false },
    { label: __('Inventory', 'bit-integrations'), key: 'inventory', required: false },
    { label: __('Tax 1', 'bit-integrations'), key: 'tax1', required: false },
    { label: __('Tax 2', 'bit-integrations'), key: 'tax2', required: false },
    { label: __('Unit Cost Amount', 'bit-integrations'), key: 'unitCostAmount', required: false },
    { label: __('Unit Cost Code', 'bit-integrations'), key: 'unitCostCode', required: false }
  ],
  updateItem: [
    { label: __('Name', 'bit-integrations'), key: 'name', required: false },
    { label: __('Description', 'bit-integrations'), key: 'description', required: false },
    { label: __('SKU', 'bit-integrations'), key: 'sku', required: false },
    { label: __('Quantity', 'bit-integrations'), key: 'qty', required: false },
    { label: __('Inventory', 'bit-integrations'), key: 'inventory', required: false },
    { label: __('Tax 1', 'bit-integrations'), key: 'tax1', required: false },
    { label: __('Tax 2', 'bit-integrations'), key: 'tax2', required: false },
    { label: __('Unit Cost Amount', 'bit-integrations'), key: 'unitCostAmount', required: false },
    { label: __('Unit Cost Code', 'bit-integrations'), key: 'unitCostCode', required: false }
  ],
  deleteItem: [],
  createTax: [
    { label: __('Name', 'bit-integrations'), key: 'name', required: true },
    { label: __('Amount', 'bit-integrations'), key: 'amount', required: false },
    { label: __('Number', 'bit-integrations'), key: 'number', required: false },
    { label: __('Compound', 'bit-integrations'), key: 'compound', required: false }
  ],
  updateTax: [
    { label: __('Name', 'bit-integrations'), key: 'name', required: false },
    { label: __('Amount', 'bit-integrations'), key: 'amount', required: false },
    { label: __('Number', 'bit-integrations'), key: 'number', required: false },
    { label: __('Compound', 'bit-integrations'), key: 'compound', required: false }
  ],
  deleteTax: [],
  createCreditNote: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: true },
    { label: __('Credit Number', 'bit-integrations'), key: 'creditNumber', required: true },
    { label: __('Credit Type', 'bit-integrations'), key: 'creditType', required: true },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: true },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: true },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false }
  ],
  updateCreditNote: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Credit Number', 'bit-integrations'), key: 'creditNumber', required: false },
    { label: __('Credit Type', 'bit-integrations'), key: 'creditType', required: false },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false }
  ],
  deleteCreditNote: [],
  createBill: [
    { label: __('Vendor ID', 'bit-integrations'), key: 'vendorId', required: true },
    { label: __('Bill Number', 'bit-integrations'), key: 'billNumber', required: false },
    { label: __('Issue Date', 'bit-integrations'), key: 'issueDate', required: false },
    { label: __('Due Date', 'bit-integrations'), key: 'dueDate', required: false },
    { label: __('Due Offset Days', 'bit-integrations'), key: 'dueOffsetDays', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false }
  ],
  updateBill: [
    { label: __('Vendor ID', 'bit-integrations'), key: 'vendorId', required: false },
    { label: __('Bill Number', 'bit-integrations'), key: 'billNumber', required: false },
    { label: __('Issue Date', 'bit-integrations'), key: 'issueDate', required: false },
    { label: __('Due Date', 'bit-integrations'), key: 'dueDate', required: false },
    { label: __('Due Offset Days', 'bit-integrations'), key: 'dueOffsetDays', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('Language', 'bit-integrations'), key: 'language', required: false }
  ],
  deleteBill: [],
  createProject: [
    { label: __('Title', 'bit-integrations'), key: 'title', required: true },
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: true },
    { label: __('Project Type', 'bit-integrations'), key: 'projectType', required: true },
    { label: __('Fixed Price', 'bit-integrations'), key: 'fixedPrice', required: false },
    { label: __('Rate', 'bit-integrations'), key: 'rate', required: false },
    { label: __('Budget', 'bit-integrations'), key: 'budget', required: false },
    { label: __('Due Date', 'bit-integrations'), key: 'dueDate', required: false },
    { label: __('Billing Method', 'bit-integrations'), key: 'billingMethod', required: false },
    { label: __('Description', 'bit-integrations'), key: 'description', required: false },
    { label: __('Internal', 'bit-integrations'), key: 'internal', required: false }
  ],
  updateProject: [
    { label: __('Title', 'bit-integrations'), key: 'title', required: false },
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Project Type', 'bit-integrations'), key: 'projectType', required: false },
    { label: __('Fixed Price', 'bit-integrations'), key: 'fixedPrice', required: false },
    { label: __('Rate', 'bit-integrations'), key: 'rate', required: false },
    { label: __('Budget', 'bit-integrations'), key: 'budget', required: false },
    { label: __('Due Date', 'bit-integrations'), key: 'dueDate', required: false },
    { label: __('Billing Method', 'bit-integrations'), key: 'billingMethod', required: false },
    { label: __('Description', 'bit-integrations'), key: 'description', required: false },
    { label: __('Internal', 'bit-integrations'), key: 'internal', required: false }
  ],
  deleteProject: [],
  createTimeEntry: [
    { label: __('Duration', 'bit-integrations'), key: 'duration', required: true },
    { label: __('Is Logged', 'bit-integrations'), key: 'isLogged', required: true },
    { label: __('Started At', 'bit-integrations'), key: 'startedAt', required: true },
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Note', 'bit-integrations'), key: 'note', required: false },
    { label: __('Project ID', 'bit-integrations'), key: 'projectId', required: false },
    { label: __('Service ID', 'bit-integrations'), key: 'serviceId', required: false },
    { label: __('Identity ID', 'bit-integrations'), key: 'identityId', required: false },
    { label: __('Billable', 'bit-integrations'), key: 'billable', required: false }
  ],
  updateTimeEntry: [
    { label: __('Duration', 'bit-integrations'), key: 'duration', required: false },
    { label: __('Is Logged', 'bit-integrations'), key: 'isLogged', required: false },
    { label: __('Started At', 'bit-integrations'), key: 'startedAt', required: false },
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Note', 'bit-integrations'), key: 'note', required: false },
    { label: __('Project ID', 'bit-integrations'), key: 'projectId', required: false },
    { label: __('Service ID', 'bit-integrations'), key: 'serviceId', required: false },
    { label: __('Identity ID', 'bit-integrations'), key: 'identityId', required: false },
    { label: __('Billable', 'bit-integrations'), key: 'billable', required: false }
  ],
  deleteTimeEntry: [],
  createService: [
    { label: __('Name', 'bit-integrations'), key: 'name', required: true },
    { label: __('Billable', 'bit-integrations'), key: 'billable', required: false }
  ],
  createRecurring: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: true },
    { label: __('Frequency', 'bit-integrations'), key: 'frequency', required: true },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: false },
    { label: __('Number Recurring', 'bit-integrations'), key: 'numberRecurring', required: false },
    { label: __('Invoice Number', 'bit-integrations'), key: 'invoiceNumber', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('PO Number', 'bit-integrations'), key: 'poNumber', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false },
    { label: __('Send Email', 'bit-integrations'), key: 'sendEmail', required: false },
    { label: __('Disable', 'bit-integrations'), key: 'disable', required: false }
  ],
  updateRecurring: [
    { label: __('Client ID', 'bit-integrations'), key: 'clientId', required: false },
    { label: __('Frequency', 'bit-integrations'), key: 'frequency', required: false },
    { label: __('Create Date', 'bit-integrations'), key: 'createDate', required: false },
    { label: __('Number Recurring', 'bit-integrations'), key: 'numberRecurring', required: false },
    { label: __('Invoice Number', 'bit-integrations'), key: 'invoiceNumber', required: false },
    { label: __('Currency Code', 'bit-integrations'), key: 'currencyCode', required: false },
    { label: __('PO Number', 'bit-integrations'), key: 'poNumber', required: false },
    { label: __('Notes', 'bit-integrations'), key: 'notes', required: false },
    { label: __('Terms', 'bit-integrations'), key: 'terms', required: false },
    { label: __('Send Email', 'bit-integrations'), key: 'sendEmail', required: false },
    { label: __('Disable', 'bit-integrations'), key: 'disable', required: false }
  ],
  deleteRecurring: []
}
