// eslint-disable-next-line import/prefer-default-export
export const webhookIntegrations = [
  'Webhook',
  'KaliForms',
  'Amelia',
  'WPFunnels',
  'Typebot',
  'JetForm',
  'FluentSupport'
]

export const customFormIntegrations = [
  'Breakdance',
  'Elementor',
  'Kadence',
  'Divi',
  'SiteOriginWidgets',
  'Bricksforge',
  'PopupMaker',
  'DiviFormBuilder',
  'Bricks',
  'Bricksforge',
  'Brizy',
  'GutenaForms',
  'PieForms',
  'Asgaros',
  'AvadaForms',
  'FluentCommunity',
  'Buddypress',
  'NinjaTables',
  'AdvancedAds',
  'AdvancedCoupons',
  'AppointmentHourBooking',
  'BetterMessages',
  'ConvertPro',
  'FunnelKitAutomations',
  'CalculatedFieldsForm',
  'AmeliaBooking',
  'FluentSMTP',
  'BbPress',
  'Newsletter',
  'WishlistMember',
  'GravityKit',
  'AdvancedCustomFields',
  'PrestoPlayer',
  'SimplyScheduleAppointments',
  'LearnPress',
  'PeepSo',
  'SureMail',
  'MasteriyoLMS',
  'FluentBoards',
  'JetpackCRM',
  'Paymattic',
  'ProfileGrid',
  'MemberPressCourse',
]

export const actionHookIntegrations = ['ActionHook']
export const customTriggerIntegrations = ['CustomTrigger']
export const freeTriggers = ['BitForm', 'CF7', 'CustomTrigger', 'Elementor', 'WC', 'WPF']
